// Package gates evaluates hand-authored and autogenerated draft rules against
// pick candidates. Kind and action strings are the shared vocabulary with the
// JS twin; keep them exact.
package gates

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"

	"poolguide/internal/config"
)

// Condition kinds.
const (
	KindEnemyVisible            = "enemyVisible"
	KindEnemyVisibleAny         = "enemyVisibleAny"
	KindEnemyVisibleNone        = "enemyVisibleNone"
	KindEnemyVisibleAnyCountMin = "enemyVisibleAnyCountMin"
	KindAllyVisibleAny          = "allyVisibleAny"
	KindEnemyCountMin           = "enemyCountMin"
	KindEnemyCountMax           = "enemyCountMax"
	KindEnemyAoEMax             = "enemyAoEMax"
	KindEnemyAoEMin             = "enemyAoEMin"
	KindRoleCandidatesGated     = "roleCandidatesGated"
	KindMinEnemyCount           = "minEnemyCount"
)

// Rule actions.
const (
	ActionHardGate = "hard_gate"
	ActionPenalty  = "penalty"
	ActionBonus    = "bonus"
	ActionNoteOnly = "note_only"
)

type Condition struct {
	Kind          string   `json:"kind"`
	Heroes        []string `json:"heroes,omitempty"`
	Count         int      `json:"count,omitempty"`
	Min           int      `json:"min,omitempty"`
	Max           int      `json:"max,omitempty"`
	MinEnemyCount int      `json:"minEnemyCount,omitempty"`
}

type Rule struct {
	Id     string      `json:"id"`
	Target string      `json:"target"`
	Roles  []string    `json:"roles,omitempty"`
	When   []Condition `json:"when"`
	Action string      `json:"action"`
	Note   string      `json:"note,omitempty"`
	Origin string      `json:"origin,omitempty"`
}

// Doc mirrors picker/gates.json.
type Doc struct {
	RoleNotes     map[string]string   `json:"roleNotes"`
	FallbackOrder map[string][]string `json:"fallbackOrder"`
	Rules         []Rule              `json:"rules"`
	Autogenerated []Rule              `json:"autogenerated"`
}

// DraftState is the visible draft at evaluation time, in hero slugs.
type DraftState struct {
	VisibleEnemies  []string
	Allies          []string
	Taken           []string
	Banned          []string
	PhaseEnemyCount int
	Role            string
	CandidatesGated int
}

// Result accumulates the effect of every rule that fired for one candidate.
type Result struct {
	HardGated    bool
	Delta        float64
	Notes        []string
	FiredRuleIds []string
}

// Eligible reports whether the candidate survives: hard gates exclude.
func (r Result) Eligible() bool {
	return !r.HardGated
}

// VsRow is one matchup row feeding Autoseed.
type VsRow struct {
	EnemySlug string
	Dis       float64
}

// Load parses a gates document from disk.
func Load(path string) (*Doc, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc Doc
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("gates: %w", err)
	}
	return &doc, nil
}

// Validate rejects malformed rules so bad data fails loudly instead of
// silently never firing.
func (d *Doc) Validate() error {
	seen := map[string]bool{}
	for _, r := range append(append([]Rule(nil), d.Rules...), d.Autogenerated...) {
		if r.Id == "" {
			return fmt.Errorf("gates: rule with empty id")
		}
		if seen[r.Id] {
			return fmt.Errorf("gates: duplicate rule id %q", r.Id)
		}
		seen[r.Id] = true
		if r.Target == "" {
			return fmt.Errorf("gates: rule %q has empty target", r.Id)
		}
		if !validAction(r.Action) {
			return fmt.Errorf("gates: rule %q has unknown action %q", r.Id, r.Action)
		}
		for _, cond := range r.When {
			if !validCondition(cond) {
				return fmt.Errorf("gates: rule %q has invalid condition %+v", r.Id, cond)
			}
		}
	}
	return nil
}

func validAction(a string) bool {
	switch a {
	case ActionHardGate, ActionPenalty, ActionBonus, ActionNoteOnly:
		return true
	}
	return false
}

func validCondition(c Condition) bool {
	switch c.Kind {
	case KindEnemyVisible, KindEnemyVisibleAny, KindEnemyVisibleNone,
		KindEnemyVisibleAnyCountMin, KindAllyVisibleAny:
		return len(c.Heroes) > 0
	case KindEnemyCountMin, KindEnemyCountMax, KindEnemyAoEMax, KindEnemyAoEMin,
		KindRoleCandidatesGated, KindMinEnemyCount:
		return true
	}
	return false
}

// Evaluate applies every rule targeting the candidate in this draft state.
// Rules fire independently; the result accumulates all of them.
func Evaluate(rules []Rule, target string, s DraftState, c *config.Config) Result {
	var res Result
	for _, r := range rules {
		if r.Target != target || !roleMatches(r, s) {
			continue
		}
		fired := true
		for _, cond := range r.When {
			if !condHolds(cond, s, c) {
				fired = false
				break
			}
		}
		if !fired {
			continue
		}
		res.FiredRuleIds = append(res.FiredRuleIds, r.Id)
		if r.Note != "" {
			res.Notes = append(res.Notes, r.Note)
		}
		switch r.Action {
		case ActionHardGate:
			res.HardGated = true
		case ActionPenalty:
			res.Delta += c.GateDeltas["penalty"]
		case ActionBonus:
			res.Delta += c.GateDeltas["bonus"]
		}
	}
	return res
}

func roleMatches(r Rule, s DraftState) bool {
	if len(r.Roles) == 0 {
		return true
	}
	for _, role := range r.Roles {
		if role == s.Role {
			return true
		}
	}
	return false
}

func condHolds(c Condition, s DraftState, cfg *config.Config) bool {
	switch c.Kind {
	case KindEnemyVisible:
		return containsAll(s.VisibleEnemies, c.Heroes)
	case KindEnemyVisibleAny:
		return containsAny(s.VisibleEnemies, c.Heroes)
	case KindEnemyVisibleNone:
		return !containsAny(s.VisibleEnemies, c.Heroes)
	case KindEnemyVisibleAnyCountMin:
		return countIn(s.VisibleEnemies, c.Heroes) >= c.Count
	case KindAllyVisibleAny:
		return containsAny(s.Allies, c.Heroes)
	case KindEnemyCountMin:
		return len(s.VisibleEnemies) >= c.Count
	case KindEnemyCountMax:
		return len(s.VisibleEnemies) <= c.Count
	case KindEnemyAoEMax:
		return countAoE(s, cfg) <= c.Max
	case KindEnemyAoEMin:
		return countAoE(s, cfg) >= c.Min
	case KindRoleCandidatesGated:
		return s.CandidatesGated >= c.Count
	case KindMinEnemyCount:
		return len(s.VisibleEnemies) >= c.MinEnemyCount
	}
	return false
}

func countAoE(s DraftState, cfg *config.Config) int {
	set := make(map[string]bool, len(cfg.AoEClearHeroes))
	for _, h := range cfg.AoEClearHeroes {
		set[h] = true
	}
	n := 0
	for _, e := range s.VisibleEnemies {
		if set[e] {
			n++
		}
	}
	return n
}

func containsAny(haystack, needles []string) bool {
	for _, n := range needles {
		for _, h := range haystack {
			if h == n {
				return true
			}
		}
	}
	return false
}

func containsAll(haystack, needles []string) bool {
	for _, n := range needles {
		found := false
		for _, h := range haystack {
			if h == n {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return len(needles) > 0
}

func countIn(haystack, needles []string) int {
	n := 0
	for _, needle := range needles {
		for _, h := range haystack {
			if h == needle {
				n++
				break
			}
		}
	}
	return n
}

// Autoseed drafts up to thresholds.autoseedCap hard-gate veto rules for the
// enemies the hero struggles most against, for review before promotion into
// the authored set. Dormant: no production caller today; if reactivated, feed
// it rows on the same z scale thresholds.disCut now names (the guide's
// matchup z), not any raw source dis.
func Autoseed(heroSlug string, vsRows []VsRow, c *config.Config) []Rule {
	var kept []VsRow
	for _, row := range vsRows {
		if row.Dis >= c.Thresholds.DisCut {
			kept = append(kept, row)
		}
	}
	sort.Slice(kept, func(i, j int) bool {
		if kept[i].Dis != kept[j].Dis {
			return kept[i].Dis > kept[j].Dis
		}
		return kept[i].EnemySlug < kept[j].EnemySlug
	})
	if len(kept) > c.Thresholds.AutoseedCap {
		kept = kept[:c.Thresholds.AutoseedCap]
	}
	rules := make([]Rule, 0, len(kept))
	for _, row := range kept {
		rules = append(rules, Rule{
			Id:     "autoseed-" + heroSlug + "-" + row.EnemySlug,
			Target: heroSlug,
			When:   []Condition{{Kind: KindEnemyVisibleAny, Heroes: []string{row.EnemySlug}}},
			Action: ActionHardGate,
			Note:   "autogenerated: " + row.EnemySlug + " dis " + strconv.FormatFloat(row.Dis, 'f', -1, 64),
			Origin: "autogenerated",
		})
	}
	return rules
}
