package emit

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"poolguide/internal/config"
)

// Prose mirrors the authored sections of content.json.
type Prose struct {
	Patch struct {
		Headline    string   `json:"headline"`
		Facts       []string `json:"facts"`
		Corrections []string `json:"corrections"`
	} `json:"patch"`
	Heroes     map[string]ProseHero `json:"heroes"`
	Principles []ProsePrinciple     `json:"principles"`
	Practice   ProsePractice        `json:"practice"`
	Picker     ProsePicker          `json:"picker"`
}

type ProseHero struct {
	Identity  string     `json:"identity"`
	Why       string     `json:"why"`
	How       string     `json:"how"`
	When      string     `json:"when"`
	Build     string     `json:"build"`
	Timings   []Timing   `json:"timings"`
	Tech      []string   `json:"tech"`
	Mechanics []Mechanic `json:"mechanics"`
}

type Timing struct {
	Label string
	At    float64
}

func (t *Timing) UnmarshalJSON(b []byte) error {
	var pair []any
	if err := json.Unmarshal(b, &pair); err != nil {
		return err
	}
	if len(pair) != 2 {
		return fmt.Errorf("timing pair has %d fields, want 2", len(pair))
	}
	label, ok := pair[0].(string)
	if !ok {
		return fmt.Errorf("timing label %v is not a string", pair[0])
	}
	at, ok := pair[1].(float64)
	if !ok {
		return fmt.Errorf("timing minute %v is not a number", pair[1])
	}
	t.Label, t.At = label, at
	return nil
}

// Mechanic is one grounded mechanics line. Tag "tip" is how the hero works,
// "counter" is how enemies interact with it; the lines are curated from
// howdoiplay.com per ref/dota2/howdoiplay/curated.json provenance. Compact
// [tag, text] pairs in content.json, mirroring Timing.
type Mechanic struct {
	Tag  string
	Text string
}

func (m *Mechanic) UnmarshalJSON(b []byte) error {
	var pair []any
	if err := json.Unmarshal(b, &pair); err != nil {
		return err
	}
	if len(pair) != 2 {
		return fmt.Errorf("mechanic pair has %d fields, want 2", len(pair))
	}
	tag, ok := pair[0].(string)
	if !ok {
		return fmt.Errorf("mechanic tag %v is not a string", pair[0])
	}
	if tag != "tip" && tag != "counter" {
		return fmt.Errorf("mechanic tag %q is not tip or counter", tag)
	}
	text, ok := pair[1].(string)
	if !ok {
		return fmt.Errorf("mechanic text %v is not a string", pair[1])
	}
	m.Tag, m.Text = tag, text
	return nil
}

type ProsePrinciple struct {
	Name string `json:"name"`
	Body string `json:"body"`
}

type ProsePractice struct {
	Warmup      []string   `json:"warmup"`
	Drills      [][]string `json:"drills"`
	Replay      []string   `json:"replay"`
	Calibration []string   `json:"calibration"`
	Bo5         []string   `json:"bo5"`
}

// ProsePicker is the guide's orientation to the pick simulator: an intro
// line plus {name, body} cards in the principles shape.
type ProsePicker struct {
	Intro string           `json:"intro"`
	Cards []ProsePrinciple `json:"cards"`
}

// LoadProse reads and validates the authored prose file.
func LoadProse(path string) (*Prose, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var p Prose
	if err := json.Unmarshal(b, &p); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &p, nil
}

// dataJSHeader is frozen verbatim: the committed guide/data.js carries
// these bytes and the emitter must reproduce that file exactly.
const dataJSHeader = `// generated by the engine emit data from config.json (pool, roles),
// the mined heatmap enemy columns, and content.json (authored prose),
// do not edit by hand.
`

// drillsPerLine is the fixed drill pair wrapping of the committed file.
const drillsPerLine = 2

// dataJSLineWidth caps the why/how/when field packing inside one pool entry;
// frozen by the committed file (short fields share one line, longer prose
// gets one field per line).
const dataJSLineWidth = 100

// DataJS merges the config hub (roles, pool) with the mined heatmap enemy
// columns and the authored prose into the GUIDE data script. The enemies come
// from the heatmap_enemies derived table in rank order; layout details that
// are not derived (trailing comma placement per section, one slug per line,
// two drills per line) are frozen by the committed guide/data.js.
func DataJS(cfg *config.Config, prose *Prose, enemies []string) ([]byte, error) {
	if len(enemies) == 0 {
		return nil, fmt.Errorf("emit: heatmap enemies required")
	}
	if len(enemies) != cfg.Heatmap.EnemyCount {
		return nil, fmt.Errorf("emit: heatmap enemies hold %d slugs, hub enemyCount is %d", len(enemies), cfg.Heatmap.EnemyCount)
	}
	if prose.Picker.Intro == "" || len(prose.Picker.Cards) == 0 {
		return nil, fmt.Errorf("emit: content.json picker orientation block missing")
	}
	var b strings.Builder
	b.WriteString(dataJSHeader)
	b.WriteString("window.GUIDE = {\n")
	writePatchSection(&b, prose)
	writeRolesSection(&b, cfg)
	if err := writePoolSection(&b, cfg, prose); err != nil {
		return nil, err
	}
	b.WriteString("  heatmapEnemies: [\n")
	for i, e := range enemies {
		comma := ","
		if i == len(enemies)-1 {
			comma = ""
		}
		b.WriteString("    " + quoteJS(e) + comma + "\n")
	}
	b.WriteString("  ],\n")
	writePrinciplesSection(&b, prose)
	writePracticeSection(&b, prose)
	writePickerSection(&b, prose)
	b.WriteString("};\n")
	return []byte(b.String()), nil
}

func writePatchSection(b *strings.Builder, prose *Prose) {
	b.WriteString("  patch: {\n")
	b.WriteString("    headline: " + quoteJS(prose.Patch.Headline) + ",\n")
	b.WriteString("    facts: [\n")
	writePlainList(b, prose.Patch.Facts)
	b.WriteString("    ],\n")
	b.WriteString("    corrections: [\n")
	writePlainList(b, prose.Patch.Corrections)
	b.WriteString("    ],\n")
	b.WriteString("  },\n")
}

// writePlainList emits one 6-space indented string per line with a trailing
// comma on every element (facts and corrections style).
func writePlainList(b *strings.Builder, items []string) {
	for _, s := range items {
		b.WriteString("      " + quoteJS(s) + ",\n")
	}
}

func writeRolesSection(b *strings.Builder, cfg *config.Config) {
	b.WriteString("  roles: [\n")
	for _, r := range cfg.Roles {
		b.WriteString("    { id: " + quoteJS(r.ID) + ", label: " + quoteJS(r.Label) + " },\n")
	}
	b.WriteString("  ],\n")
}

// guideHeroes returns the pool heroes in hub declaration order (first
// occurrence of each slug) with merged roles and the first entry's tier,
// matching how the committed file was assembled.
func guideHeroes(cfg *config.Config) []config.Hero {
	bySlug := map[string]*config.Hero{}
	var order []string
	for _, e := range cfg.Pool {
		h, ok := bySlug[e.Slug]
		if !ok {
			h = &config.Hero{Slug: e.Slug, Name: e.Name, Tier: map[string]string{}, Roles: []string{}}
			h.Tier[""] = e.Tier
			bySlug[e.Slug] = h
			order = append(order, e.Slug)
		}
		h.Roles = append(h.Roles, e.Role)
		h.Tier[e.Role] = e.Tier
	}
	out := make([]config.Hero, 0, len(order))
	for _, s := range order {
		h := bySlug[s]
		sortStrings(h.Roles)
		out = append(out, *h)
	}
	return out
}

func sortStrings(xs []string) {
	for i := 1; i < len(xs); i++ {
		for j := i; j > 0 && xs[j] < xs[j-1]; j-- {
			xs[j], xs[j-1] = xs[j-1], xs[j]
		}
	}
}

func writePoolSection(b *strings.Builder, cfg *config.Config, prose *Prose) error {
	b.WriteString("  pool: [\n")
	for _, h := range guideHeroes(cfg) {
		p, ok := prose.Heroes[h.Slug]
		if !ok {
			return fmt.Errorf("emit: content.json has no prose for pool hero %s", h.Slug)
		}
		roles := make([]string, len(h.Roles))
		for i, r := range h.Roles {
			roles[i] = quoteJS(r)
		}
		tier := h.Tier[""]
		b.WriteString("    { slug: " + quoteJS(h.Slug) + ", name: " + quoteJS(h.Name) +
			", roles: [" + strings.Join(roles, ", ") + "], tier: " + quoteJS(tier) + ",\n")
		b.WriteString("      identity: " + quoteJS(p.Identity) + ",\n")
		writeWhyHowWhen(b, p)
		writeWrappedFields(b, ",", []string{
			"build: " + quoteJS(p.Build) + ",",
			"timings: " + jsTimings(p.Timings) + ",",
			"tech: " + jsStrings(p.Tech) + ",",
			"mechanics: " + jsMechanics(p.Mechanics) + " }",
		})
	}
	b.WriteString("  ],\n")
	return nil
}

// writeWhyHowWhen packs the three prose fields onto as few 6-space indented
// lines as the frozen line width allows.
func writeWhyHowWhen(b *strings.Builder, p ProseHero) {
	writeWrappedFields(b, "", []string{
		"why: " + quoteJS(p.Why) + ",",
		"how: " + quoteJS(p.How) + ",",
		"when: " + quoteJS(p.When) + ",",
	})
}

// writeWrappedFields emits the field chunks on one 6-space indented line when
// the joined line fits the frozen width, otherwise one chunk per line. The
// committed file uses this all-or-nothing packing, not greedy packing.
// suffix lands on the final line.
func writeWrappedFields(b *strings.Builder, suffix string, chunks []string) {
	joined := strings.Join(chunks, " ")
	lines := []string{joined}
	if len(joined)+len(suffix) > dataJSLineWidth {
		lines = chunks
	}
	for i, l := range lines {
		s := ""
		if i == len(lines)-1 {
			s = suffix
		}
		b.WriteString("      " + l + s + "\n")
	}
}

func jsTimings(ts []Timing) string {
	parts := make([]string, len(ts))
	for i, t := range ts {
		parts[i] = "[" + quoteJS(t.Label) + ", " + fmtShort(t.At) + "]"
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func jsStrings(xs []string) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = quoteJS(x)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func jsMechanics(ms []Mechanic) string {
	parts := make([]string, len(ms))
	for i, m := range ms {
		parts[i] = "[" + quoteJS(m.Tag) + ", " + quoteJS(m.Text) + "]"
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func writePrinciplesSection(b *strings.Builder, prose *Prose) {
	b.WriteString("  principles: [\n")
	for _, p := range prose.Principles {
		b.WriteString("    { name: " + quoteJS(p.Name) + ", body: " + quoteJS(p.Body) + " },\n")
	}
	b.WriteString("  ],\n")
}

func writePracticeSection(b *strings.Builder, prose *Prose) {
	b.WriteString("  practice: {\n")
	b.WriteString("    warmup: " + jsStrings(prose.Practice.Warmup) + ",\n")
	b.WriteString("    drills: [\n")
	pairs := make([]string, len(prose.Practice.Drills))
	for i, d := range prose.Practice.Drills {
		pairs[i] = jsStrings(d)
	}
	if len(pairs) > 0 {
		b.WriteString("      ")
	}
	for i, p := range pairs {
		if i == len(pairs)-1 {
			b.WriteString(p + "\n")
			break
		}
		sep := " "
		if (i+1)%drillsPerLine == 0 {
			sep = "\n      "
		}
		b.WriteString(p + "," + sep)
	}
	b.WriteString("    ],\n")
	b.WriteString("    replay: " + jsStrings(prose.Practice.Replay) + ",\n")
	b.WriteString("    calibration: " + jsStrings(prose.Practice.Calibration) + ",\n")
	b.WriteString("    bo5: " + jsStrings(prose.Practice.Bo5) + ",\n")
	b.WriteString("  },\n")
}

func writePickerSection(b *strings.Builder, prose *Prose) {
	b.WriteString("  picker: {\n")
	b.WriteString("    intro: " + quoteJS(prose.Picker.Intro) + ",\n")
	b.WriteString("    cards: [\n")
	for _, c := range prose.Picker.Cards {
		b.WriteString("      { name: " + quoteJS(c.Name) + ", body: " + quoteJS(c.Body) + " },\n")
	}
	b.WriteString("    ],\n")
	b.WriteString("  },\n")
}
