package emit

import (
	"database/sql"
	"fmt"
	"sort"
	"strings"

	"poolguide/internal/config"
	"poolguide/internal/mine"
)

// RosterHero is one hero_roster row.
type RosterHero struct {
	ID   int
	Slug string
	Name string
	NPC  string
}

// GuideRow is one mined matchup cell for a pool hero: dis is the negated
// within-hero matchup z from norm_cell (sd units, observed cells only),
// positive = the enemy beats the pool hero. Scale-free, so the threshold and
// the page ramp hold their meaning across sources and alphas. Src is the
// pair_shrunk tier backing the cell, so backup-filled rows are attributable.
type GuideRow struct {
	Enemy string
	Dis   float64
	Src   string
}

// GuideInput carries everything the guide artifact needs.
type GuideInput struct {
	Date        string
	Roster      []RosterHero          // hero_id ascending
	PriorWR     map[string]float64    // pool slug -> shrunk overall win rate in [0,1]
	Rows        map[string][]GuideRow // pool slug -> mined enemy cells
	Scraped     map[string]string     // pool slug -> stratz_vs crawl date
	Trend       map[string]TrendCell  // pool slug -> latest-pair movement
	TrendWindow string                // 'from to' when any trend delta exists
}

// guideHeaderLine1 is frozen verbatim: the committed guide artifact carries
// this attribution and the retired PowerShell build stays the parity oracle.
const guideHeaderLine1 = "// generated by scripts/build-guide-data.ps1, do not edit by hand"

// guideSourceNoteFmt renders the stratz_vs provenance note; the shape is
// frozen by the committed artifact. Backup-backed kept rows append a counted
// suffix so the note never attributes backup data to the stratz crawl.
const guideSourceNoteFmt = "stratz_vs crawl %s"

// matchupSrcStratzVS is the matchup_raw.source vocabulary shared with the
// ingest layer (see the store schema comment).
const matchupSrcStratzVS = "stratz_vs"

// FormatGuide renders guide-data-generated.js. sources and matchups list the
// pool heroes that have mined coverage, slug ascending; overallWr covers
// every pool hero from the mined hero_prior table. heroes whose filtered rows
// fall under thresholds.minKept fail the build rather than shipping a thin
// guide section.
func FormatGuide(in GuideInput, cfg *config.Config) ([]byte, error) {
	var heroes []string
	for slug := range in.Rows {
		heroes = append(heroes, slug)
	}
	sort.Strings(heroes)

	var b strings.Builder
	b.WriteString(guideHeaderLine1 + "\n")
	b.WriteString("// packed rows: enemySlug:dis (dis = negated matchup z in sd, positive = enemy beats pool hero), |dis| >= " +
		fmtShort(cfg.Thresholds.DisCut) + "\n")
	b.WriteString("window.GUIDE_GEN = {\n")
	b.WriteString("  date: " + quoteJS(in.Date) + ",\n")
	b.WriteString("  threshold: " + fmtShort(cfg.Thresholds.DisCut) + ",\n")

	keptByHero := map[string][]GuideRow{}
	for _, slug := range heroes {
		kept := filterGuideRows(in.Rows[slug], cfg.Thresholds.DisCut)
		if len(kept) < cfg.Thresholds.MinKept {
			return nil, fmt.Errorf("emit: guide hero %s kept %d rows at |dis| >= %s, want >= %d",
				slug, len(kept), fmtShort(cfg.Thresholds.DisCut), cfg.Thresholds.MinKept)
		}
		keptByHero[slug] = kept
	}

	b.WriteString("  sources: {\n")
	for _, slug := range heroes {
		note := fmt.Sprintf(guideSourceNoteFmt, in.Scraped[slug]) + backupSuffix(keptByHero[slug])
		b.WriteString("    " + quoteJS(slug) + ": " + quoteJS(note) + ",\n")
	}
	b.WriteString("  },\n")

	b.WriteString("  overallWr: {\n")
	for _, slug := range cfg.PoolSlugs() {
		wr, ok := in.PriorWR[slug]
		if !ok {
			return nil, fmt.Errorf("emit: no overall win rate for guide hero %s", slug)
		}
		b.WriteString("    " + quoteJS(slug) + ": " + fmtShort(wr*100) + ",\n")
	}
	b.WriteString("  },\n")

	b.WriteString("  trend: {\n")
	for _, slug := range heroes {
		td, ok := in.Trend[slug]
		if !ok {
			continue
		}
		b.WriteString("    " + quoteJS(slug) + ": [" + fmtShort(td.WrDeltaPP) + ", " + fmtShort(td.ShareDeltaPP) + "],\n")
	}
	b.WriteString("  },\n")
	b.WriteString("  trendWindow: " + quoteJS(in.TrendWindow) + ",\n")

	b.WriteString("  matchups: {\n")
	for _, slug := range heroes {
		kept := keptByHero[slug]
		parts := make([]string, len(kept))
		for i, r := range kept {
			parts[i] = r.Enemy + ":" + fmtShort(r.Dis)
		}
		b.WriteString("    " + quoteJS(slug) + ": " + quoteJS(strings.Join(parts, "|")) + ",\n")
	}
	b.WriteString("  },\n")

	b.WriteString("  iconBySlug: {\n")
	for _, h := range rosterBySlug(in.Roster) {
		b.WriteString("    " + quoteJS(h.Slug) + ": " + quoteJS(config.ShortNPC(h.NPC)) + ",\n")
	}
	b.WriteString("  }\n};\n")
	return []byte(b.String()), nil
}

// backupSuffix counts kept rows backed by a non-stratz tier, source names
// ascending, so the guide note attributes backup-filled pairs honestly.
func backupSuffix(rows []GuideRow) string {
	counts := map[string]int{}
	for _, r := range rows {
		if r.Src != "" && r.Src != mine.SrcStratz {
			counts[r.Src]++
		}
	}
	if len(counts) == 0 {
		return ""
	}
	srcs := make([]string, 0, len(counts))
	for s := range counts {
		srcs = append(srcs, s)
	}
	sort.Strings(srcs)
	parts := make([]string, len(srcs))
	for i, s := range srcs {
		parts[i] = fmt.Sprintf("+%d %s", counts[s], s)
	}
	return " (" + strings.Join(parts, ", ") + ")"
}

// filterGuideRows keeps |dis| >= cut, dis descending, enemy ascending on ties.
func filterGuideRows(rows []GuideRow, cut float64) []GuideRow {
	var kept []GuideRow
	for _, r := range rows {
		if r.Dis >= cut || r.Dis <= -cut {
			kept = append(kept, r)
		}
	}
	sort.Slice(kept, func(i, j int) bool {
		if kept[i].Dis != kept[j].Dis {
			return kept[i].Dis > kept[j].Dis
		}
		return kept[i].Enemy < kept[j].Enemy
	})
	return kept
}

// rosterBySlug returns the roster sorted by slug ascending.
func rosterBySlug(roster []RosterHero) []RosterHero {
	out := append([]RosterHero(nil), roster...)
	sort.Slice(out, func(i, j int) bool { return out[i].Slug < out[j].Slug })
	return out
}

// LoadGuide reads the guide inputs from the derived and raw tables: the
// roster, the mined overall win rates, and the observed enemy cells. The
// crawl covers every pair, but rows failing the sanity gate are treated as
// uncovered and the backup tier fills them, so each row carries the
// pair_shrunk tier that actually backs it.
func LoadGuide(db *sql.DB, cfg *config.Config) (GuideInput, error) {
	roster, err := LoadRoster(db)
	if err != nil {
		return GuideInput{}, err
	}
	prior := map[string]float64{}
	rows, err := db.Query(`SELECT slug, wr FROM hero_prior`)
	if err != nil {
		return GuideInput{}, fmt.Errorf("hero_prior: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var slug string
		var wr float64
		if err := rows.Scan(&slug, &wr); err != nil {
			return GuideInput{}, err
		}
		prior[slug] = wr
	}
	if err := rows.Err(); err != nil {
		return GuideInput{}, err
	}

	in := GuideInput{Roster: roster, PriorWR: prior, Rows: map[string][]GuideRow{}, Scraped: map[string]string{}, Trend: map[string]TrendCell{}}
	rows, err = db.Query(`SELECT slug, wr_delta_pp, share_delta_pp, from_date, to_date FROM hero_trend_delta`)
	if err != nil {
		return GuideInput{}, fmt.Errorf("hero_trend_delta: %w", err)
	}
	for rows.Next() {
		var slug string
		var tc TrendCell
		if err := rows.Scan(&slug, &tc.WrDeltaPP, &tc.ShareDeltaPP, &tc.FromDate, &tc.ToDate); err != nil {
			rows.Close()
			return GuideInput{}, err
		}
		in.Trend[slug] = tc
		if tc.FromDate+" to "+tc.ToDate > in.TrendWindow {
			in.TrendWindow = tc.FromDate + " to " + tc.ToDate
		}
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return GuideInput{}, err
	}
	rows.Close()

	rows, err = db.Query(`SELECT nc.hero, nc.other, nc.z, ps.source
		FROM norm_cell nc LEFT JOIN pair_shrunk ps
		ON ps.hero = nc.hero AND ps.other = nc.other AND ps.kind = nc.kind
		WHERE nc.kind = ? AND nc.completed = false`, mine.KindEnemy)
	if err != nil {
		return GuideInput{}, fmt.Errorf("norm_cell: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var hero, other string
		var z float64
		var src sql.NullString
		if err := rows.Scan(&hero, &other, &z, &src); err != nil {
			return GuideInput{}, err
		}
		in.Rows[hero] = append(in.Rows[hero], GuideRow{Enemy: other, Dis: -z, Src: src.String})
	}
	if err := rows.Err(); err != nil {
		return GuideInput{}, err
	}
	rows, err = db.Query(`SELECT pool_slug, MAX(scrape_date) FROM matchup_raw WHERE source = ? GROUP BY pool_slug`, matchupSrcStratzVS)
	if err != nil {
		return GuideInput{}, fmt.Errorf("matchup_raw: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var pool, scraped string
		if err := rows.Scan(&pool, &scraped); err != nil {
			return GuideInput{}, err
		}
		in.Scraped[pool] = scraped
	}
	return in, rows.Err()
}
