package emit

import (
	"database/sql"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"poolguide/internal/analytics"
	"poolguide/internal/config"
	"poolguide/internal/gates"
)

// PickerCell is one normalized matchup or synergy value for a pool hero.
type PickerCell struct {
	Pct       float64
	Completed bool
	Conf      int // 0 high, 1 medium, 2 low
}

// HeroPosStat is one farm-position stat for a pool hero, display only: the
// hero's pick share at the position (share of the hero's own picks) and the
// win rate there.
type HeroPosStat struct {
	Position int
	Share    float64
	WR       float64
}

// TrendCell is the latest-pair trend movement for a pool hero, display
// only: overall wr and pick share deltas in pp between the two most recent
// snapshot dates in the trends ledger.
type TrendCell struct {
	WrDeltaPP, ShareDeltaPP float64
	FromDate, ToDate        string
}

// PickerInput carries everything the picker artifact needs.
type PickerInput struct {
	Date       string
	Roster     []RosterHero                     // hero_id ascending
	Pop        map[string]float64               // slug -> pick share
	Mu         map[string]map[string]PickerCell // pool slug -> other slug -> cell
	Syn        map[string]map[string]PickerCell
	Prior      map[string]float64 // pool slug -> raw prior value
	HeroPos    map[string][]HeroPosStat
	Trend      map[string]TrendCell
	HeroSource map[string]string  // pool slug -> stratz | opendota_explorer
	Prose      map[string]ProseHero // pool slug -> authored framework prose
	Gates      *gates.Doc
}

// pickerWindowNote derives the data-window semantics line from the hub take
// so it can never drift: winDay windows roll, the pair and item tables pin
// the last completed calendar week.
func pickerWindowNote(take int) string {
	return fmt.Sprintf("stratz %d-day window, pairs on the last completed week, not patch pure", take)
}

// proseLine renders one pool hero's framework prose as a compact js object.
// Hand-rendered because Timing carries no json tags, so jsValue would emit
// the exported field names.
func proseLine(p ProseHero) string {
	timings := make([]string, len(p.Timings))
	for i, t := range p.Timings {
		timings[i] = "[" + quoteJS(t.Label) + ", " + fmtShort(t.At) + "]"
	}
	tech := make([]string, len(p.Tech))
	for i, s := range p.Tech {
		tech[i] = quoteJS(s)
	}
	mechanics := make([]string, len(p.Mechanics))
	for i, m := range p.Mechanics {
		mechanics[i] = "[" + quoteJS(m.Tag) + ", " + quoteJS(m.Text) + "]"
	}
	return "{ identity: " + quoteJS(p.Identity) +
		", why: " + quoteJS(p.Why) +
		", how: " + quoteJS(p.How) +
		", when: " + quoteJS(p.When) +
		", build: " + quoteJS(p.Build) +
		", timings: [" + strings.Join(timings, ", ") + "]" +
		", tech: [" + strings.Join(tech, ", ") + "]" +
		", mechanics: [" + strings.Join(mechanics, ", ") + "] }"
}

// pickerHeader is the generated-artifact marker for the picker output.
const pickerHeader = "// generated by the engine emit picker, do not edit by hand"

// FormatPicker renders picker-data-generated.js per picker/DATA-CONTRACT.md:
// parallel arrays in hero_id order, poolIdx ascending, mu/syn packed rows
// covering every roster hero, prior as the midrank percentile of the mined
// prior values.
func FormatPicker(in PickerInput, cfg *config.Config) ([]byte, error) {
	if in.Gates == nil {
		return nil, fmt.Errorf("emit: picker input requires a gates document")
	}
	idxOf := map[string]int{}
	slugs := make([]string, len(in.Roster))
	names := make([]string, len(in.Roster))
	icons := make([]string, len(in.Roster))
	pop := make([]string, len(in.Roster))
	for i, h := range in.Roster {
		idxOf[h.Slug] = i
		slugs[i], names[i], icons[i] = quoteJS(h.Slug), quoteJS(h.Name), quoteJS(config.ShortNPC(h.NPC))
		share, ok := in.Pop[h.Slug]
		if !ok {
			return nil, fmt.Errorf("emit: no popularity for roster hero %s", h.Slug)
		}
		pop[i] = fmtFixed(share, cfg.Emit.Decimals)
	}

	pool := cfg.PoolSlugs()
	poolIdx := make([]int, len(pool))
	entries := make([]string, len(pool))
	proseLines := make([]string, len(pool))
	muRows := make([]string, len(pool))
	synRows := make([]string, len(pool))
	priorVals := make([]float64, len(pool))
	posLines := make([]string, len(pool))
	trendLines := make([]string, len(pool))
	for pi, slug := range pool {
		idx, ok := idxOf[slug]
		if !ok {
			return nil, fmt.Errorf("emit: pool hero %s missing from roster", slug)
		}
		poolIdx[pi] = idx
		h := cfg.HeroBySlug(slug)
		roles := make([]string, len(h.Roles))
		tier := make([]string, len(h.Roles))
		for ri, r := range h.Roles {
			roles[ri] = quoteJS(r)
			tier[ri] = quoteJS(r) + ": " + quoteJS(h.Tier[r])
		}
		entries[pi] = "{ roles: [" + strings.Join(roles, ", ") + "], tier: { " + strings.Join(tier, ", ") + " } }"
		p, ok := in.Prose[slug]
		if !ok {
			return nil, fmt.Errorf("emit: no prose for pool hero %s", slug)
		}
		proseLines[pi] = proseLine(p)
		var err error
		if muRows[pi], err = packedRow(in.Mu[slug], idxOf, len(in.Roster), cfg.Emit.Decimals); err != nil {
			return nil, fmt.Errorf("mu %s: %w", slug, err)
		}
		if synRows[pi], err = packedRow(in.Syn[slug], idxOf, len(in.Roster), cfg.Emit.Decimals); err != nil {
			return nil, fmt.Errorf("syn %s: %w", slug, err)
		}
		v, ok := in.Prior[slug]
		if !ok {
			return nil, fmt.Errorf("emit: no prior for pool hero %s", slug)
		}
		priorVals[pi] = v
		stats := in.HeroPos[slug]
		parts := make([]string, len(stats))
		for si, s := range stats {
			parts[si] = fmt.Sprintf("[%d, %s, %s]", s.Position,
				fmtFixed(s.Share, cfg.Emit.Decimals), fmtFixed(s.WR, cfg.Emit.Decimals))
		}
		posLines[pi] = "[" + strings.Join(parts, ", ") + "]"
		if td, ok := in.Trend[slug]; ok {
			trendLines[pi] = fmt.Sprintf("[%s, %s]",
				fmtFixed(td.WrDeltaPP, cfg.Emit.Decimals), fmtFixed(td.ShareDeltaPP, cfg.Emit.Decimals))
		} else {
			trendLines[pi] = "null"
		}
	}
	priorPcts := analytics.Midrank(priorVals)

	// search/display-only alias pairs: keep those whose canonical slug is a
	// roster hero and whose key does not itself shadow a roster slug, so the
	// picker search never ranks an alias against nothing.
	aliases := make(map[string]string, len(cfg.Aliases))
	for k, v := range cfg.Aliases {
		if _, ok := idxOf[v]; ok {
			if _, clash := idxOf[k]; !clash {
				aliases[k] = v
			}
		}
	}

	var b strings.Builder
	b.WriteString(pickerHeader + "\n")
	b.WriteString("window.PICKER_GEN = {\n")
	b.WriteString("  date: " + quoteJS(in.Date) + ",\n")
	b.WriteString("  patch: " + quoteJS(cfg.Patch) + ",\n")
	fmt.Fprintf(&b, "  rosterCount: %d,\n", len(in.Roster))
	b.WriteString("  slugs: [" + strings.Join(slugs, ", ") + "],\n")
	b.WriteString("  names: [" + strings.Join(names, ", ") + "],\n")
	b.WriteString("  icons: [" + strings.Join(icons, ", ") + "],\n")
	b.WriteString("  pop: [" + strings.Join(pop, ", ") + "],\n")
	b.WriteString("  aliases: " + jsValue(aliases) + ",\n")
	b.WriteString("  poolIdx: [" + intsJoin(poolIdx) + "],\n")
	b.WriteString("  entries: [\n")
	for _, e := range entries {
		b.WriteString("    " + e + ",\n")
	}
	b.WriteString("  ],\n")
	b.WriteString("  prose: [\n")
	for _, p := range proseLines {
		b.WriteString("    " + p + ",\n")
	}
	b.WriteString("  ],\n")
	b.WriteString("  mu: [" + strings.Join(quoteAll(muRows), ", ") + "],\n")
	b.WriteString("  syn: [" + strings.Join(quoteAll(synRows), ", ") + "],\n")
	prior := make([]string, len(priorPcts))
	for i, p := range priorPcts {
		prior[i] = fmtFixed(p, cfg.Emit.Decimals)
	}
	b.WriteString("  prior: [" + strings.Join(prior, ", ") + "],\n")
	b.WriteString("  heroPos: [\n")
	for _, line := range posLines {
		b.WriteString("    " + line + ",\n")
	}
	b.WriteString("  ],\n")
	b.WriteString("  trend: [\n")
	for _, line := range trendLines {
		b.WriteString("    " + line + ",\n")
	}
	b.WriteString("  ],\n")
	b.WriteString("  roles: " + jsValue(cfg.Roles) + ",\n")
	b.WriteString("  weights: " + jsValue(cfg.Weights) + ",\n")
	b.WriteString("  scoreConsts: " + jsValue(cfg.Score) + ",\n")
	b.WriteString("  meta: {\n")
	b.WriteString("    bracket: " + quoteJS(cfg.Scope.Bracket) + ",\n")
	b.WriteString("    window: " + quoteJS(pickerWindowNote(cfg.Stratz.Take)) + ",\n")
	b.WriteString("    perHeroSource: " + jsValue(in.HeroSource) + "\n")
	b.WriteString("  },\n")
	b.WriteString("  gates: {\n")
	b.WriteString("    roleNotes: " + jsValue(in.Gates.RoleNotes) + ",\n")
	b.WriteString("    fallbackOrder: " + jsValue(in.Gates.FallbackOrder) + ",\n")
	b.WriteString("    rules: " + jsValue(in.Gates.Rules) + ",\n")
	b.WriteString("    autogenerated: " + jsValue(in.Gates.Autogenerated) + ",\n")
	b.WriteString("    gateDeltas: " + jsValue(cfg.GateDeltas) + ",\n")
	b.WriteString("    aoeClearHeroes: " + jsValue(cfg.AoEClearHeroes) + "\n")
	b.WriteString("  }\n};\n")
	return []byte(b.String()), nil
}

// packedRow renders one 'idx:pct:conf,...' row covering every roster index.
func packedRow(cells map[string]PickerCell, idxOf map[string]int, rosterLen, dec int) (string, error) {
	if cells == nil {
		return "", fmt.Errorf("no cells")
	}
	parts := make([]string, 0, rosterLen)
	for slug, i := range idxOf {
		c, ok := cells[slug]
		if !ok {
			return "", fmt.Errorf("no cell for roster hero %s", slug)
		}
		parts = append(parts, fmt.Sprintf("%d:%s:%d", i, fmtFixed(c.Pct, dec), c.Conf))
	}
	sort.Slice(parts, func(a, b int) bool {
		return partIdx(parts[a]) < partIdx(parts[b])
	})
	return strings.Join(parts, ","), nil
}

// partIdx reads the roster index prefix of one packed entry.
func partIdx(s string) int {
	head, _, _ := strings.Cut(s, ":")
	n, _ := strconv.Atoi(head)
	return n
}

func intsJoin(xs []int) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprintf("%d", x)
	}
	return strings.Join(parts, ", ")
}

func quoteAll(xs []string) []string {
	out := make([]string, len(xs))
	for i, x := range xs {
		out[i] = quoteJS(x)
	}
	return out
}

// LoadRoster reads hero_roster in hero_id ascending order.
func LoadRoster(db *sql.DB) ([]RosterHero, error) {
	rows, err := db.Query(`SELECT hero_id, slug, name, npc FROM hero_roster ORDER BY hero_id`)
	if err != nil {
		return nil, fmt.Errorf("hero_roster: %w", err)
	}
	defer rows.Close()
	var out []RosterHero
	for rows.Next() {
		var h RosterHero
		if err := rows.Scan(&h.ID, &h.Slug, &h.Name, &h.NPC); err != nil {
			return nil, err
		}
		out = append(out, h)
	}
	return out, rows.Err()
}

// LoadPicker reads the picker inputs from the derived tables plus the roster.
// Completed cells carry the lowest confidence; observed cells inherit the
// confidence mined into pair_shrunk. perHeroSource is the enemy-cell
// majority source per pool hero, ties broken alphabetically.
func LoadPicker(db *sql.DB, cfg *config.Config, doc *gates.Doc) (PickerInput, error) {
	roster, err := LoadRoster(db)
	if err != nil {
		return PickerInput{}, err
	}
	in := PickerInput{
		Date:       "",
		Roster:     roster,
		Pop:        map[string]float64{},
		Mu:         map[string]map[string]PickerCell{},
		Syn:        map[string]map[string]PickerCell{},
		Prior:      map[string]float64{},
		HeroSource: map[string]string{},
		Gates:      doc,
	}
	rows, err := db.Query(`SELECT slug, pick_share FROM popularity`)
	if err != nil {
		return in, fmt.Errorf("popularity: %w", err)
	}
	for rows.Next() {
		var slug string
		var share float64
		if err := rows.Scan(&slug, &share); err != nil {
			rows.Close()
			return in, err
		}
		in.Pop[slug] = share
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return in, err
	}
	rows.Close()

	rows, err = db.Query(`SELECT slug, value FROM hero_prior`)
	if err != nil {
		return in, fmt.Errorf("hero_prior: %w", err)
	}
	for rows.Next() {
		var slug string
		var v float64
		if err := rows.Scan(&slug, &v); err != nil {
			rows.Close()
			return in, err
		}
		in.Prior[slug] = v
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return in, err
	}
	rows.Close()

	in.HeroPos = map[string][]HeroPosStat{}
	in.Trend = map[string]TrendCell{}
	rows, err = db.Query(`SELECT slug, wr_delta_pp, share_delta_pp, from_date, to_date FROM hero_trend_delta`)
	if err != nil {
		return in, fmt.Errorf("hero_trend_delta: %w", err)
	}
	for rows.Next() {
		var slug string
		var tc TrendCell
		if err := rows.Scan(&slug, &tc.WrDeltaPP, &tc.ShareDeltaPP, &tc.FromDate, &tc.ToDate); err != nil {
			rows.Close()
			return in, err
		}
		in.Trend[slug] = tc
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return in, err
	}
	rows.Close()

	rows, err = db.Query(`SELECT slug, position, pick_count, win_count FROM hero_position`)
	if err != nil {
		return in, fmt.Errorf("hero_position: %w", err)
	}
	type posRaw struct {
		position   int
		picks      int64
		wins       int64
	}
	raw := map[string][]posRaw{}
	var heroTotal = map[string]int64{}
	for rows.Next() {
		var slug string
		var r posRaw
		if err := rows.Scan(&slug, &r.position, &r.picks, &r.wins); err != nil {
			rows.Close()
			return in, err
		}
		raw[slug] = append(raw[slug], r)
		heroTotal[slug] += r.picks
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return in, err
	}
	rows.Close()
	for slug, rs := range raw {
		total := heroTotal[slug]
		if total <= 0 {
			continue
		}
		stats := make([]HeroPosStat, 0, len(rs))
		for _, r := range rs {
			if r.picks <= 0 {
				continue
			}
			stats = append(stats, HeroPosStat{
				Position: r.position,
				Share:    float64(r.picks) / float64(total),
				WR:       float64(r.wins) / float64(r.picks),
			})
		}
		sort.Slice(stats, func(i, j int) bool {
			if stats[i].Share != stats[j].Share {
				return stats[i].Share > stats[j].Share
			}
			return stats[i].Position < stats[j].Position
		})
		in.HeroPos[slug] = stats
	}

	rows, err = db.Query(`SELECT nc.hero, nc.other, nc.kind, nc.pct, nc.completed, ps.source, ps.confidence
		FROM norm_cell nc LEFT JOIN pair_shrunk ps
		ON ps.hero = nc.hero AND ps.other = nc.other AND ps.kind = nc.kind`)
	if err != nil {
		return in, fmt.Errorf("norm_cell: %w", err)
	}
	defer rows.Close()
	srcCount := map[string]map[string]int{}
	for rows.Next() {
		var hero, other, kind string
		var pct float64
		var completed bool
		var src, confLabel sql.NullString
		if err := rows.Scan(&hero, &other, &kind, &pct, &completed, &src, &confLabel); err != nil {
			return in, err
		}
		conf := confRankOf(confLabel.String)
		if completed || !confLabel.Valid {
			conf = 2
		}
		cell := PickerCell{Pct: pct, Completed: completed, Conf: conf}
		switch kind {
		case "enemy":
			if in.Mu[hero] == nil {
				in.Mu[hero] = map[string]PickerCell{}
			}
			in.Mu[hero][other] = cell
		case "ally":
			if in.Syn[hero] == nil {
				in.Syn[hero] = map[string]PickerCell{}
			}
			in.Syn[hero][other] = cell
		}
		if kind == "enemy" && src.Valid {
			if srcCount[hero] == nil {
				srcCount[hero] = map[string]int{}
			}
			for _, s := range strings.Split(src.String, "+") {
				srcCount[hero][s]++
			}
		}
	}
	if err := rows.Err(); err != nil {
		return in, err
	}
	for hero, counts := range srcCount {
		best, bestN := "", -1
		var labels []string
		for s := range counts {
			labels = append(labels, s)
		}
		sort.Strings(labels)
		for _, s := range labels {
			if counts[s] > bestN {
				best, bestN = s, counts[s]
			}
		}
		in.HeroSource[hero] = best
	}
	return in, nil
}

// confRankOf maps the mined confidence label (pair_shrunk.confidence) to the
// contract rank; unknown labels read as low. It must never be fed the source
// column: source values are tier names and would flatten every cell to low.
func confRankOf(label string) int {
	switch label {
	case "high":
		return 0
	case "medium":
		return 1
	}
	return 2
}
