package emit

import (
	"os"
	"path/filepath"
)

// WriteFile persists generated bytes, creating parent directories.
func WriteFile(path string, b []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}
