package order

import (
	"database/sql"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"poolguide/internal/config"
	"poolguide/internal/store"
)

func loadHubCfg(t *testing.T) *config.Config {
	t.Helper()
	cfg, err := config.Load("../../../config.json")
	if err != nil {
		t.Fatalf("load hub config: %v", err)
	}
	// fixtures sort every role; a test that cares about the pin sets it itself
	cfg.OrderPinnedRoles = nil
	return cfg
}

// fixturePool interleaves roles so the rewrite must visibly regroup them.
func fixturePool() []config.PoolEntry {
	return []config.PoolEntry{
		{Slug: "hero-b", Name: "Hero B", Role: "1", Tier: "dedicated"},
		{Slug: "hero-e", Name: "Hero E", Role: "2", Tier: "dedicated"},
		{Slug: "hero-a", Name: "Hero A", Role: "1", Tier: "dedicated"},
		{Slug: "hero-g", Name: "Hero G", Role: "3", Tier: "dedicated"},
		{Slug: "hero-i", Name: "Hero I", Role: "4", Tier: "dedicated"},
		{Slug: "hero-c", Name: "Hero C", Role: "1", Tier: "dedicated"},
		{Slug: "hero-f", Name: "Hero F", Role: "2", Tier: "dedicated"},
		{Slug: "hero-h", Name: "Hero H", Role: "3", Tier: "dedicated"},
		{Slug: "hero-j", Name: "Hero J", Role: "4", Tier: "dedicated"},
		{Slug: "hero-k", Name: "Hero K", Role: "5", Tier: "dedicated"},
		{Slug: "hero-l", Name: "Hero L", Role: "5", Tier: "dedicated"},
	}
}

type posFix struct {
	slug       string
	position   int
	picks, win int64
}

// fixturePositions builds the wr/pick ladder: role 1 exercises the wr-desc
// then picks-desc tiebreak (c .60, b .55/200, a .55/100), role 2 the slug-asc
// tiebreak (e and f identical).
func fixturePositions() []posFix {
	return []posFix{
		{"hero-c", 1, 300, 180},
		{"hero-b", 1, 200, 110},
		{"hero-a", 1, 100, 55},
		{"hero-e", 2, 100, 50},
		{"hero-f", 2, 100, 50},
		{"hero-h", 3, 50, 35},
		{"hero-g", 3, 900, 360},
		{"hero-i", 4, 400, 180},
		{"hero-j", 4, 10, 5},
		{"hero-k", 5, 5, 3},
		{"hero-l", 5, 9999, 4900},
	}
}

func fixtureStats() map[string]map[int]posStat {
	stats := map[string]map[int]posStat{}
	for _, f := range fixturePositions() {
		if stats[f.slug] == nil {
			stats[f.slug] = map[int]posStat{}
		}
		stats[f.slug][f.position] = posStat{WR: float64(f.win) / float64(f.picks), PickCount: f.picks}
	}
	return stats
}

// expectedFlatten is the canonical output: roles in hub order, wr order within.
func expectedOrder() []string {
	return []string{
		"hero-c", "hero-b", "hero-a",
		"hero-e", "hero-f",
		"hero-h", "hero-g",
		"hero-j", "hero-i",
		"hero-k", "hero-l",
	}
}

func insertPositions(t *testing.T, db *sql.DB, rows []posFix) {
	t.Helper()
	for _, f := range rows {
		if _, err := db.Exec(`INSERT INTO hero_position (slug, position, pick_count, win_count, source, scrape_date)
			VALUES (?, ?, ?, ?, 'stratz_winday', '2026-09-27')`, f.slug, f.position, f.picks, f.win); err != nil {
			t.Fatalf("insert hero_position %s@%d: %v", f.slug, f.position, err)
		}
	}
}

func writeFixtureConfig(t *testing.T, path string, pool []config.PoolEntry) []byte {
	t.Helper()
	raw, err := os.ReadFile("../../../config.json")
	if err != nil {
		t.Fatalf("read hub config: %v", err)
	}
	var hub map[string]any
	if err := json.Unmarshal(raw, &hub); err != nil {
		t.Fatalf("parse hub config: %v", err)
	}
	pb, err := json.Marshal(pool)
	if err != nil {
		t.Fatalf("marshal fixture pool: %v", err)
	}
	var poolAny []any
	if err := json.Unmarshal(pb, &poolAny); err != nil {
		t.Fatalf("reparse fixture pool: %v", err)
	}
	hub["pool"] = poolAny
	hub["decoy"] = map[string]any{"nested": []any{1, "two", true}}
	out, err := json.MarshalIndent(hub, "", "  ")
	if err != nil {
		t.Fatalf("marshal fixture config: %v", err)
	}
	out = append(out, '\n')
	if err := os.WriteFile(path, out, 0o644); err != nil {
		t.Fatalf("write fixture config: %v", err)
	}
	if _, err := config.Load(path); err != nil {
		t.Fatalf("fixture config does not load: %v", err)
	}
	return out
}

func writeFixtureGates(t *testing.T, path string, fallback map[string][]string) []byte {
	t.Helper()
	doc := map[string]any{
		"roleNotes": map[string]any{
			"1": "note one", "2": "note two", "3": "note three", "4": "note four", "5": "note five",
		},
		"fallbackOrder": fallback,
		"rules":         []any{},
		"autogenerated": []any{},
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		t.Fatalf("marshal fixture gates: %v", err)
	}
	out = append(out, '\n')
	if err := os.WriteFile(path, out, 0o644); err != nil {
		t.Fatalf("write fixture gates: %v", err)
	}
	return out
}

func fixtureFallback() map[string][]string {
	return map[string][]string{
		"1": {"hero-a", "hero-c", "hero-b"},
		"2": {"hero-f", "hero-e"},
		"3": {"hero-g", "hero-h"},
		"4": {"hero-i", "hero-j"},
		"5": {"hero-l", "hero-k"},
	}
}

// fixture wires a temp repo: config file, gates file, and a duckdb seeded with
// hero_position rows.
type fixture struct {
	cfg        *config.Config
	cfgPath    string
	gatesPath  string
	cfgBytes   []byte
	gatesBytes []byte
	db         *sql.DB
}

func newFixture(t *testing.T) *fixture {
	t.Helper()
	dir := t.TempDir()
	cfg := loadHubCfg(t)
	cfg.Pool = fixturePool()
	cfg.Paths.PickerDir = dir
	f := &fixture{
		cfg:       cfg,
		cfgPath:   filepath.Join(dir, "config.json"),
		gatesPath: filepath.Join(dir, "gates.json"),
	}
	f.cfgBytes = writeFixtureConfig(t, f.cfgPath, cfg.Pool)
	f.gatesBytes = writeFixtureGates(t, f.gatesPath, fixtureFallback())
	db, err := store.Open(filepath.Join(dir, "fixture.duckdb"))
	if err != nil {
		t.Fatalf("open fixture db: %v", err)
	}
	t.Cleanup(func() { db.Close() })
	insertPositions(t, db, fixturePositions())
	f.db = db
	return f
}

func (f *fixture) run(t *testing.T) error {
	t.Helper()
	return Run(Deps{DB: f.db, Cfg: f.cfg, CfgPath: f.cfgPath})
}

func readBytes(t *testing.T, path string) []byte {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return b
}

func TestRoleOrdersSortsByWrThenPicksThenSlug(t *testing.T) {
	cfg := loadHubCfg(t)
	cfg.Pool = fixturePool()
	ordered, err := roleOrders(cfg, fixtureStats())
	if err != nil {
		t.Fatalf("roleOrders: %v", err)
	}
	var flat []string
	for _, r := range cfg.Roles {
		for _, e := range ordered[r.ID] {
			flat = append(flat, e.Slug)
		}
	}
	if !reflect.DeepEqual(flat, expectedOrder()) {
		t.Fatalf("roleOrders order = %v, want %v", flat, expectedOrder())
	}
}

func TestRoleOrdersFailsListingEveryMissingRow(t *testing.T) {
	cfg := loadHubCfg(t)
	cfg.Pool = fixturePool()
	stats := fixtureStats()
	delete(stats["hero-c"], 1)
	stats["hero-k"][5] = posStat{WR: 0.5, PickCount: 0} // zero picks is missing data too
	_, err := roleOrders(cfg, stats)
	if err == nil {
		t.Fatal("roleOrders should fail on missing rows")
	}
	for _, want := range []string{"hero-c@1", "hero-k@5"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("error %q does not name %s", err, want)
		}
	}
}

func TestRunRewritesPoolAndFallbackSorted(t *testing.T) {
	f := newFixture(t)
	if err := f.run(t); err != nil {
		t.Fatalf("run: %v", err)
	}

	var hub map[string]any
	if err := json.Unmarshal(readBytes(t, f.cfgPath), &hub); err != nil {
		t.Fatalf("parse rendered config: %v", err)
	}
	var got []string
	for _, e := range hub["pool"].([]any) {
		m := e.(map[string]any)
		got = append(got, m["slug"].(string))
	}
	if !reflect.DeepEqual(got, expectedOrder()) {
		t.Fatalf("rendered pool order = %v, want %v", got, expectedOrder())
	}
	if _, ok := hub["decoy"]; !ok {
		t.Fatal("rendered config lost the decoy key")
	}

	var doc map[string]any
	if err := json.Unmarshal(readBytes(t, f.gatesPath), &doc); err != nil {
		t.Fatalf("parse rendered gates: %v", err)
	}
	fallback := doc["fallbackOrder"].(map[string]any)
	wantByRole := map[string][]string{
		"1": {"hero-c", "hero-b", "hero-a"},
		"2": {"hero-e", "hero-f"},
		"3": {"hero-h", "hero-g"},
		"4": {"hero-j", "hero-i"},
		"5": {"hero-k", "hero-l"},
	}
	for role, want := range wantByRole {
		var gotRole []string
		for _, s := range fallback[role].([]any) {
			gotRole = append(gotRole, s.(string))
		}
		if !reflect.DeepEqual(gotRole, want) {
			t.Fatalf("fallbackOrder[%s] = %v, want %v", role, gotRole, want)
		}
	}
}

func TestRunPreservesEveryOtherField(t *testing.T) {
	f := newFixture(t)
	if err := f.run(t); err != nil {
		t.Fatalf("run: %v", err)
	}
	var cfgBefore, cfgAfter map[string]any
	if err := json.Unmarshal(f.cfgBytes, &cfgBefore); err != nil {
		t.Fatalf("parse before: %v", err)
	}
	if err := json.Unmarshal(readBytes(t, f.cfgPath), &cfgAfter); err != nil {
		t.Fatalf("parse after: %v", err)
	}
	for k, vb := range cfgBefore {
		if k == "pool" {
			continue
		}
		if !reflect.DeepEqual(vb, cfgAfter[k]) {
			t.Fatalf("rendered config changed top-level %s", k)
		}
	}
	for k := range cfgAfter {
		if _, ok := cfgBefore[k]; !ok {
			t.Fatalf("rendered config added top-level %s", k)
		}
	}
	var gatesBefore, gatesAfter map[string]any
	if err := json.Unmarshal(f.gatesBytes, &gatesBefore); err != nil {
		t.Fatalf("parse gates before: %v", err)
	}
	if err := json.Unmarshal(readBytes(t, f.gatesPath), &gatesAfter); err != nil {
		t.Fatalf("parse gates after: %v", err)
	}
	for k, vb := range gatesBefore {
		if k == "fallbackOrder" {
			continue
		}
		if !reflect.DeepEqual(vb, gatesAfter[k]) {
			t.Fatalf("rendered gates changed top-level %s", k)
		}
	}
	// and byte-for-byte outside the spliced regions
	cfgOut := readBytes(t, f.cfgPath)
	valAt, err := findTopLevelValue(cfgOut, "pool")
	if err != nil {
		t.Fatalf("anchor: %v", err)
	}
	closeAt, err := matchBracket(cfgOut, valAt)
	if err != nil {
		t.Fatalf("bracket: %v", err)
	}
	if string(cfgOut[:valAt+1]) != string(f.cfgBytes[:valAt+1]) ||
		string(cfgOut[closeAt:]) != string(f.cfgBytes[closeAt:]) {
		t.Fatal("rendered config changed bytes outside the pool array")
	}
}

func TestRunIsIdempotent(t *testing.T) {
	f := newFixture(t)
	if err := f.run(t); err != nil {
		t.Fatalf("first run: %v", err)
	}
	firstCfg := readBytes(t, f.cfgPath)
	firstGates := readBytes(t, f.gatesPath)
	if err := f.run(t); err != nil {
		t.Fatalf("second run: %v", err)
	}
	if string(firstCfg) != string(readBytes(t, f.cfgPath)) {
		t.Fatal("second run rewrote config.json")
	}
	if string(firstGates) != string(readBytes(t, f.gatesPath)) {
		t.Fatal("second run rewrote gates.json")
	}
}

func TestRoleOrdersKeepsPinnedDeclarationOrder(t *testing.T) {
	cfg := loadHubCfg(t)
	pool := fixturePool()
	// declare role 5 opposite to its win-rate order: hero-l (0.49) outranks
	// nothing, hero-k (0.60) is the win-rate head, the pin must keep l first
	last := len(pool) - 1
	pool[last-1], pool[last] = pool[last], pool[last-1]
	cfg.Pool = pool
	cfg.OrderPinnedRoles = []string{"5"}
	ordered, err := roleOrders(cfg, fixtureStats())
	if err != nil {
		t.Fatalf("roleOrders: %v", err)
	}
	var flat []string
	for _, r := range cfg.Roles {
		for _, e := range ordered[r.ID] {
			flat = append(flat, e.Slug)
		}
	}
	want := []string{
		"hero-c", "hero-b", "hero-a",
		"hero-e", "hero-f",
		"hero-h", "hero-g",
		"hero-j", "hero-i",
		"hero-l", "hero-k", // declaration order survives the pin
	}
	if !reflect.DeepEqual(flat, want) {
		t.Fatalf("roleOrders order = %v, want %v", flat, want)
	}
}

func TestRunKeepsPinnedRoleDeclarationOrder(t *testing.T) {
	f := newFixture(t)
	pool := fixturePool()
	last := len(pool) - 1
	pool[last-1], pool[last] = pool[last], pool[last-1]
	f.cfg.Pool = pool
	f.cfg.OrderPinnedRoles = []string{"5"}
	f.cfgBytes = writeFixtureConfig(t, f.cfgPath, pool)
	// pre-write the fallback in sorted order, opposite of the pinned
	// declaration, so the assertion below can only hold if the pinned run
	// actually rewrote it
	flipped := fixtureFallback()
	flipped["5"] = []string{"hero-k", "hero-l"}
	f.gatesBytes = writeFixtureGates(t, f.gatesPath, flipped)
	if err := f.run(t); err != nil {
		t.Fatalf("run: %v", err)
	}
	var hub map[string]any
	if err := json.Unmarshal(readBytes(t, f.cfgPath), &hub); err != nil {
		t.Fatalf("parse rendered config: %v", err)
	}
	var got []string
	for _, e := range hub["pool"].([]any) {
		m := e.(map[string]any)
		got = append(got, m["slug"].(string))
	}
	want := []string{
		"hero-c", "hero-b", "hero-a",
		"hero-e", "hero-f",
		"hero-h", "hero-g",
		"hero-j", "hero-i",
		"hero-l", "hero-k",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("rendered pool order = %v, want %v", got, want)
	}
	var doc map[string]any
	if err := json.Unmarshal(readBytes(t, f.gatesPath), &doc); err != nil {
		t.Fatalf("parse rendered gates: %v", err)
	}
	var gotRole []string
	for _, s := range doc["fallbackOrder"].(map[string]any)["5"].([]any) {
		gotRole = append(gotRole, s.(string))
	}
	if !reflect.DeepEqual(gotRole, []string{"hero-l", "hero-k"}) {
		t.Fatalf("fallbackOrder[5] = %v, want the pinned declaration order", gotRole)
	}
	// a second run over the pinned output rewrites nothing
	afterCfg := readBytes(t, f.cfgPath)
	afterGates := readBytes(t, f.gatesPath)
	if err := f.run(t); err != nil {
		t.Fatalf("second run: %v", err)
	}
	if string(afterCfg) != string(readBytes(t, f.cfgPath)) || string(afterGates) != string(readBytes(t, f.gatesPath)) {
		t.Fatal("second pinned run rewrote either file")
	}
}

// a pinned role still reports missing stat rows before any write, the pin
// never waives the data requirement
func TestRunReportsMissingRowForPinnedRole(t *testing.T) {
	f := newFixture(t)
	f.cfg.OrderPinnedRoles = []string{"5"}
	if _, err := f.db.Exec(`DELETE FROM hero_position WHERE slug = 'hero-l' AND position = 5`); err != nil {
		t.Fatalf("delete row: %v", err)
	}
	err := f.run(t)
	if err == nil {
		t.Fatal("pinned run should fail on a missing hero_position row")
	}
	if !strings.Contains(err.Error(), "hero-l@5") {
		t.Fatalf("error %q does not name hero-l@5", err)
	}
}

func TestRunWritesNothingWhenARowIsMissing(t *testing.T) {
	f := newFixture(t)
	if _, err := f.db.Exec(`DELETE FROM hero_position WHERE slug = 'hero-c' AND position = 1`); err != nil {
		t.Fatalf("delete row: %v", err)
	}
	err := f.run(t)
	if err == nil {
		t.Fatal("run should fail on a missing hero_position row")
	}
	if !strings.Contains(err.Error(), "hero-c@1") {
		t.Fatalf("error %q does not name hero-c@1", err)
	}
	if string(readBytes(t, f.cfgPath)) != string(f.cfgBytes) {
		t.Fatal("failed run still rewrote config.json")
	}
	if string(readBytes(t, f.gatesPath)) != string(f.gatesBytes) {
		t.Fatal("failed run still rewrote gates.json")
	}
}

func TestRunRejectsFallbackSetDrift(t *testing.T) {
	f := newFixture(t)
	drifted := fixtureFallback()
	drifted["1"] = []string{"hero-b", "hero-c"} // hero-a missing
	f.gatesBytes = writeFixtureGates(t, f.gatesPath, drifted)
	err := f.run(t)
	if err == nil {
		t.Fatal("run should fail when fallbackOrder disagrees with the pool")
	}
	if !strings.Contains(err.Error(), "fallbackOrder") {
		t.Fatalf("error %q does not mention fallbackOrder", err)
	}
	if string(readBytes(t, f.cfgPath)) != string(f.cfgBytes) {
		t.Fatal("failed run still rewrote config.json")
	}
}

func TestRenderMatchesCommittedShape(t *testing.T) {
	got := renderPoolEntry(config.PoolEntry{Slug: "hero-a", Name: "Hero A", Role: "1", Tier: "dedicated"})
	want := "\n    {\n      \"slug\": \"hero-a\",\n      \"name\": \"Hero A\",\n      \"role\": \"1\",\n      \"tier\": \"dedicated\"\n    }"
	if got != want {
		t.Fatalf("renderPoolEntry = %q, want %q", got, want)
	}
	gotRole := renderFallbackRole("1", []string{"hero-c", "hero-b"})
	wantRole := "\n    \"1\": [\n      \"hero-c\",\n      \"hero-b\"\n    ]"
	if gotRole != wantRole {
		t.Fatalf("renderFallbackRole = %q, want %q", gotRole, wantRole)
	}
}
