package order

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"poolguide/internal/config"
	"poolguide/internal/store"
)

// writeCfgVariant writes the hub with the fixture pool spliced in plus one
// extra mutation. unlike writeFixtureConfig it does not load the result: the
// arms below need on-disk hubs that are parseable but fail hub validation, so
// Run's read-splice-validate chain meets the bad bytes where it should.
func writeCfgVariant(t *testing.T, path string, mut func(map[string]any)) []byte {
	t.Helper()
	raw, err := os.ReadFile("../../../config.json")
	if err != nil {
		t.Fatalf("read hub config: %v", err)
	}
	var hub map[string]any
	if err := json.Unmarshal(raw, &hub); err != nil {
		t.Fatalf("parse hub config: %v", err)
	}
	pb, err := json.Marshal(fixturePool())
	if err != nil {
		t.Fatalf("marshal fixture pool: %v", err)
	}
	var poolAny []any
	if err := json.Unmarshal(pb, &poolAny); err != nil {
		t.Fatalf("reparse fixture pool: %v", err)
	}
	hub["pool"] = poolAny
	if mut != nil {
		mut(hub)
	}
	out, err := json.MarshalIndent(hub, "", "  ")
	if err != nil {
		t.Fatalf("marshal variant config: %v", err)
	}
	out = append(out, '\n')
	if err := os.WriteFile(path, out, 0o644); err != nil {
		t.Fatalf("write variant config: %v", err)
	}
	return out
}

// writeCompactGates writes the fixture gates as single-line json: parseable,
// in sync, but without the two-space-indented anchor the splice scans for.
func writeCompactGates(t *testing.T, path string) {
	t.Helper()
	doc := map[string]any{
		"roleNotes": map[string]any{
			"1": "note one", "2": "note two", "3": "note three", "4": "note four", "5": "note five",
		},
		"fallbackOrder": fixtureFallback(),
		"rules":         []any{},
		"autogenerated": []any{},
	}
	out, err := json.Marshal(doc)
	if err != nil {
		t.Fatalf("marshal compact gates: %v", err)
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		t.Fatalf("write compact gates: %v", err)
	}
}

// writeGatesWithRules writes a fixture gates doc whose rules fail validation.
func writeGatesWithRules(t *testing.T, path string, rules []any) {
	t.Helper()
	doc := map[string]any{
		"roleNotes":     map[string]any{"1": "note one", "2": "note two", "3": "note three", "4": "note four", "5": "note five"},
		"fallbackOrder": fixtureFallback(),
		"rules":         rules,
		"autogenerated": []any{},
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		t.Fatalf("marshal gates: %v", err)
	}
	out = append(out, '\n')
	if err := os.WriteFile(path, out, 0o644); err != nil {
		t.Fatalf("write gates: %v", err)
	}
}

func TestRunFailsOnClosedDB(t *testing.T) {
	f := newFixture(t)
	f.db.Close()
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), "order: load hero_position") {
		t.Fatalf("run over a closed db must fail at the hero_position load, got %v", err)
	}
}

// a NULL scrape_date scans into nothing, so the row scan fails loudly instead
// of feeding the sorter an empty date.
func TestLoadPositionWRScanError(t *testing.T) {
	db, err := store.Open(filepath.Join(t.TempDir(), "scanerr.duckdb"))
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	t.Cleanup(func() { db.Close() })
	for _, q := range []string{
		`DROP TABLE hero_position`,
		`CREATE TABLE hero_position (slug VARCHAR, position INTEGER, pick_count BIGINT,
			win_count BIGINT, scrape_date VARCHAR, source VARCHAR)`,
		`INSERT INTO hero_position VALUES ('hero-a', 1, 10, 5, NULL, 'stratz_winday')`,
	} {
		if _, err := db.Exec(q); err != nil {
			t.Fatalf("exec %q: %v", q, err)
		}
	}
	if _, _, err := loadPositionWR(db); err == nil {
		t.Fatal("loadPositionWR must fail on an unscannable row")
	}
}

func TestRoleOrdersRejectsNonNumericRole(t *testing.T) {
	cfg := loadHubCfg(t)
	cfg.Pool = fixturePool()
	cfg.Pool[0].Role = "core"
	_, err := roleOrders(cfg, fixtureStats())
	if err == nil || !strings.Contains(err.Error(), `non-numeric role "core"`) {
		t.Fatalf("roleOrders must reject a non-numeric role, got %v", err)
	}
}

func TestRunFailsWhenConfigFileMissing(t *testing.T) {
	f := newFixture(t)
	f.cfgPath = filepath.Join(t.TempDir(), "missing.json")
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), "missing.json") {
		t.Fatalf("run must fail on a missing config file, got %v", err)
	}
}

func TestRunFailsWhenGatesFileMissing(t *testing.T) {
	f := newFixture(t)
	if err := os.Remove(f.gatesPath); err != nil {
		t.Fatalf("remove gates: %v", err)
	}
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), "gates.json") {
		t.Fatalf("run must fail on a missing gates file, got %v", err)
	}
}

func TestRunFailsOnMalformedGates(t *testing.T) {
	f := newFixture(t)
	if err := os.WriteFile(f.gatesPath, []byte("{not json"), 0o644); err != nil {
		t.Fatalf("write malformed gates: %v", err)
	}
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), "gates") {
		t.Fatalf("run must fail on unparsable gates, got %v", err)
	}
}

func TestRunFailsOnInvalidGatesDoc(t *testing.T) {
	f := newFixture(t)
	writeGatesWithRules(t, f.gatesPath, []any{map[string]any{
		"id": "", "target": "hero-a", "when": []any{}, "action": "bonus",
	}})
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), "empty id") {
		t.Fatalf("run must fail when the gates doc fails its own validation, got %v", err)
	}
}

// role 5 keeps its hub role but loses every pool entry, and the fallback set
// shrinks to match, so sync holds and the empty ordered role fails the flatten.
func TestRunRejectsRoleWithNoPoolEntries(t *testing.T) {
	f := newFixture(t)
	kept := f.cfg.Pool[:0]
	for _, e := range f.cfg.Pool {
		if e.Role != "5" {
			kept = append(kept, e)
		}
	}
	f.cfg.Pool = kept
	fallback := fixtureFallback()
	fallback["5"] = []string{}
	writeFixtureGates(t, f.gatesPath, fallback)
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), "role 5 has no pool entries") {
		t.Fatalf("run must fail on a role without pool entries, got %v", err)
	}
}

func TestRunFailsWhenPoolAnchorMissing(t *testing.T) {
	f := newFixture(t)
	writeCfgVariant(t, f.cfgPath, func(hub map[string]any) { delete(hub, "pool") })
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), `top-level key "pool" not found`) {
		t.Fatalf("run must fail when the config carries no pool anchor, got %v", err)
	}
}

func TestRunFailsWhenGatesAnchorMissing(t *testing.T) {
	f := newFixture(t)
	writeCompactGates(t, f.gatesPath)
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), `top-level key "fallbackOrder" not found`) {
		t.Fatalf("run must fail when the gates carry no fallbackOrder anchor, got %v", err)
	}
}

// the on-disk hub stays parseable but invalid (emit.decimals 0), so the splice
// rides through and the pre-write reload catches it.
func TestRunFailsWhenRenderedConfigFailsHubValidation(t *testing.T) {
	f := newFixture(t)
	writeCfgVariant(t, f.cfgPath, func(hub map[string]any) {
		hub["emit"].(map[string]any)["decimals"] = 0
	})
	err := f.run(t)
	if err == nil || !strings.Contains(err.Error(), "fails hub validation") {
		t.Fatalf("run must fail when the rendered config fails hub validation, got %v", err)
	}
}

// TestRunRejectsFallbackSyncDrift covers the remaining assertGatesInSync
// problems one at a time: an unknown role key, a slug outside the pool, and a
// config role with no fallback entry at all.
func TestRunRejectsFallbackSyncDrift(t *testing.T) {
	tests := []struct {
		name   string
		mut    func(map[string][]string)
		wantEr string
	}{
		{"unknown fallback role", func(fb map[string][]string) { fb["6"] = []string{"hero-a"} },
			"role 6 is not a config role"},
		{"slug outside the pool", func(fb map[string][]string) {
			fb["1"] = []string{"hero-a", "hero-b", "hero-c", "hero-zz"}
		}, "outside the pool"},
		{"config role missing from fallback", func(fb map[string][]string) { delete(fb, "5") },
			"missing from fallbackOrder"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			fallback := fixtureFallback()
			tt.mut(fallback)
			writeFixtureGates(t, f.gatesPath, fallback)
			err := f.run(t)
			if err == nil || !strings.Contains(err.Error(), tt.wantEr) {
				t.Fatalf("run must fail on %s, got %v", tt.name, err)
			}
		})
	}
}

func TestFindTopLevelValue(t *testing.T) {
	src := []byte("{\n  \"pool\": [\n  ],\n  \"other\": 1\n}")
	at, err := findTopLevelValue(src, "pool")
	if err != nil || src[at] != '[' {
		t.Fatalf("findTopLevelValue(pool) = %d, %v", at, err)
	}
	at, err = findTopLevelValue(src, "other")
	if err != nil || src[at] != '1' {
		t.Fatalf("findTopLevelValue(other) = %d, %v", at, err)
	}
	// tabs after the colon are skipped like spaces
	tabbed := []byte("{\n  \"k\":\t[1]\n}")
	at, err = findTopLevelValue(tabbed, "k")
	if err != nil || tabbed[at] != '[' {
		t.Fatalf("findTopLevelValue over a tab-padded value = %d, %v", at, err)
	}
	if _, err := findTopLevelValue(src, "gone"); err == nil || !strings.Contains(err.Error(), "not found") {
		t.Fatalf("missing key must fail, got %v", err)
	}
	amb := []byte("{\n  \"pool\": [],\n  \"pool\": []\n}")
	if _, err := findTopLevelValue(amb, "pool"); err == nil || !strings.Contains(err.Error(), "ambiguous") {
		t.Fatalf("duplicate key must fail, got %v", err)
	}
}

func TestMatchBracket(t *testing.T) {
	// every closer sits on the last byte, so the whole-span cases pin the scan
	flat := []byte("[1, 2]")
	if at, err := matchBracket(flat, 0); err != nil || at != len(flat)-1 {
		t.Fatalf("flat array close = %d, %v", at, err)
	}
	nested := []byte(`{"a": [1]}`)
	if at, err := matchBracket(nested, 0); err != nil || at != len(nested)-1 {
		t.Fatalf("nested object close = %d, %v", at, err)
	}
	// brackets inside string literals never count
	inStr := []byte(`["a]b"]`)
	if at, err := matchBracket(inStr, 0); err != nil || at != len(inStr)-1 {
		t.Fatalf("in-string bracket must be ignored, close = %d, %v", at, err)
	}
	// an escaped quote keeps the string open across a bracket
	escaped := []byte(`{"s": "a\"]"}`)
	if at, err := matchBracket(escaped, 0); err != nil || at != len(escaped)-1 {
		t.Fatalf("escaped-quote bracket must be ignored, close = %d, %v", at, err)
	}
	if _, err := matchBracket([]byte("[1"), 0); err == nil || !strings.Contains(err.Error(), "unmatched") {
		t.Fatalf("unterminated bracket must fail, got %v", err)
	}
	if _, err := matchBracket([]byte("x"), 0); err == nil || !strings.Contains(err.Error(), "expected a bracket") {
		t.Fatalf("non-bracket opener must fail, got %v", err)
	}
}

func TestRenderErrorsOnBadAnchors(t *testing.T) {
	if _, err := renderConfigPool([]byte("{\n  \"x\": 1\n}"), fixturePool()); err == nil ||
		!strings.Contains(err.Error(), `key "pool" not found`) {
		t.Fatalf("renderConfigPool must fail without a pool anchor, got %v", err)
	}
	if _, err := renderConfigPool([]byte("{\n  \"pool\": 5\n}"), fixturePool()); err == nil ||
		!strings.Contains(err.Error(), "expected a bracket") {
		t.Fatalf("renderConfigPool must fail on a non-bracket pool value, got %v", err)
	}
	roles := []config.RoleDef{{ID: "1"}}
	if _, err := renderGatesFallback([]byte("{\n  \"x\": 1\n}"), roles, nil); err == nil ||
		!strings.Contains(err.Error(), `key "fallbackOrder" not found`) {
		t.Fatalf("renderGatesFallback must fail without an anchor, got %v", err)
	}
	if _, err := renderGatesFallback([]byte("{\n  \"fallbackOrder\": 3\n}"), roles, nil); err == nil ||
		!strings.Contains(err.Error(), "expected a bracket") {
		t.Fatalf("renderGatesFallback must fail on a non-bracket value, got %v", err)
	}
}

// TestAssertConfigPreservedArms drives every disagreement the post-render
// audit rejects, plus the happy path, over hand-shaped documents.
func TestAssertConfigPreservedArms(t *testing.T) {
	entries := func(pairs ...[2]string) []any {
		var out []any
		for _, p := range pairs {
			out = append(out, map[string]any{"slug": p[0], "role": p[1]})
		}
		return out
	}
	mustMarshal := func(v any) []byte {
		b, err := json.Marshal(v)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		return b
	}
	ordered := func(slugs ...string) []config.PoolEntry {
		out := make([]config.PoolEntry, len(slugs))
		for i, s := range slugs {
			out[i] = config.PoolEntry{Slug: s, Role: "1"}
		}
		return out
	}
	ab := entries([2]string{"a", "1"}, [2]string{"b", "1"})
	flipped := entries([2]string{"b", "1"}, [2]string{"a", "1"})
	tests := []struct {
		name string
		orig []byte
		out  []byte
		want []config.PoolEntry
		err  string
	}{
		{"orig does not parse", []byte("{oops"), mustMarshal(map[string]any{"pool": ab}), nil, "invalid character"},
		{"out does not parse", mustMarshal(map[string]any{"pool": ab}), []byte("{oops"), nil, "does not parse"},
		{"changed top-level", mustMarshal(map[string]any{"pool": ab, "patch": "a"}),
			mustMarshal(map[string]any{"pool": ab, "patch": "b"}), nil, "changed top-level patch"},
		{"added top-level", mustMarshal(map[string]any{"pool": ab}),
			mustMarshal(map[string]any{"pool": ab, "zz": 1}), nil, "added top-level zz"},
		{"membership changed", mustMarshal(map[string]any{"pool": ab}),
			mustMarshal(map[string]any{"pool": entries([2]string{"a", "1"}, [2]string{"c", "1"})}), nil, "changed the pool membership"},
		{"order mismatch", mustMarshal(map[string]any{"pool": ab}),
			mustMarshal(map[string]any{"pool": flipped}), ordered("a", "b"), "does not match the computed order"},
		{"in order", mustMarshal(map[string]any{"pool": flipped}),
			mustMarshal(map[string]any{"pool": flipped}), ordered("b", "a"), ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := assertConfigPreserved(tt.orig, tt.out, tt.want)
			if tt.err == "" {
				if err != nil {
					t.Fatalf("matching documents must pass, got %v", err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), tt.err) {
				t.Fatalf("assertConfigPreserved must fail with %q, got %v", tt.err, err)
			}
		})
	}
}

func TestAssertGatesPreservedArms(t *testing.T) {
	roles := []config.RoleDef{{ID: "1"}}
	mustMarshal := func(v any) []byte {
		b, err := json.Marshal(v)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		return b
	}
	doc := func(fb map[string]any, extra ...map[string]any) []byte {
		m := map[string]any{"fallbackOrder": fb}
		for _, e := range extra {
			for k, v := range e {
				m[k] = v
			}
		}
		return mustMarshal(m)
	}
	ordered := func(slugs ...string) map[string][]config.PoolEntry {
		out := map[string][]config.PoolEntry{}
		for _, s := range slugs {
			out["1"] = append(out["1"], config.PoolEntry{Slug: s})
		}
		return out
	}
	tests := []struct {
		name string
		orig []byte
		out  []byte
		want map[string][]config.PoolEntry
		err  string
	}{
		{"orig does not parse", []byte("{oops"), doc(map[string]any{"1": []string{"a"}}), nil, "invalid character"},
		{"out does not parse", doc(map[string]any{"1": []string{"a"}}), []byte("{oops"), nil, "does not parse"},
		{"changed top-level", doc(map[string]any{"1": []string{"a"}}, map[string]any{"note": "x"}),
			doc(map[string]any{"1": []string{"a"}}, map[string]any{"note": "y"}), nil, "changed top-level note"},
		{"added top-level", doc(map[string]any{"1": []string{"a"}}),
			doc(map[string]any{"1": []string{"a"}}, map[string]any{"zz": 1}), nil, "added top-level zz"},
		{"set changed", doc(map[string]any{"1": []string{"a", "b"}}),
			doc(map[string]any{"1": []string{"a", "c"}}), nil, "changed its set"},
		{"order mismatch", doc(map[string]any{"1": []string{"a", "b"}}),
			doc(map[string]any{"1": []string{"b", "a"}}), ordered("a", "b"), "does not match the computed order"},
		{"in order", doc(map[string]any{"1": []string{"a", "b"}}),
			doc(map[string]any{"1": []string{"a", "b"}}), ordered("a", "b"), ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := assertGatesPreserved(tt.orig, tt.out, roles, tt.want)
			if tt.err == "" {
				if err != nil {
					t.Fatalf("matching documents must pass, got %v", err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), tt.err) {
				t.Fatalf("assertGatesPreserved must fail with %q, got %v", tt.err, err)
			}
		})
	}
}

func TestMultisetEqual(t *testing.T) {
	if !multisetEqual(nil, nil) || !multisetEqual([]string{"a"}, []string{"a"}) {
		t.Fatal("equal multisets must compare equal")
	}
	if multisetEqual([]string{"a"}, []string{"a", "b"}) {
		t.Fatal("different lengths must compare unequal")
	}
	if multisetEqual([]string{"a", "a"}, []string{"a", "b"}) {
		t.Fatal("repeated keys on one side must compare unequal")
	}
}

func TestValidateRenderedConfigArms(t *testing.T) {
	valid := writeFixtureConfig(t, filepath.Join(t.TempDir(), "config.json"), fixturePool())
	if err := validateRenderedConfig([]byte("{"), fixturePool()); err == nil ||
		!strings.Contains(err.Error(), "fails hub validation") {
		t.Fatalf("unparsable rendered config must fail, got %v", err)
	}
	if err := validateRenderedConfig(valid, fixturePool()[:10]); err == nil ||
		!strings.Contains(err.Error(), "pool has 11 entries, want 10") {
		t.Fatalf("pool length drift must fail, got %v", err)
	}
	mutated := append([]config.PoolEntry(nil), fixturePool()...)
	mutated[0].Tier = "flex"
	if err := validateRenderedConfig(valid, mutated); err == nil ||
		!strings.Contains(err.Error(), "pool entry 0") {
		t.Fatalf("mutated pool entry must fail, got %v", err)
	}
	if err := validateRenderedConfig(valid, fixturePool()); err != nil {
		t.Fatalf("faithful render must validate, got %v", err)
	}
}

func TestValidateRenderedGatesArms(t *testing.T) {
	roles := []config.RoleDef{{ID: "1"}}
	if err := validateRenderedGates([]byte("{"), roles, nil); err == nil ||
		!strings.Contains(err.Error(), "does not parse") {
		t.Fatalf("unparsable rendered gates must fail, got %v", err)
	}
	invalid := []byte(`{"roleNotes": {}, "fallbackOrder": {}, "rules": [{"id": "", "target": "x", "when": [], "action": "bonus"}]}`)
	if err := validateRenderedGates(invalid, roles, nil); err == nil ||
		!strings.Contains(err.Error(), "fails validation") {
		t.Fatalf("gates failing their own validation must fail, got %v", err)
	}
	valid := writeFixtureGates(t, filepath.Join(t.TempDir(), "gates.json"), fixtureFallback())
	ordered := map[string][]config.PoolEntry{
		"1": {{Slug: "hero-b"}, {Slug: "hero-c"}, {Slug: "hero-a"}},
	}
	if err := validateRenderedGates(valid, roles, ordered); err == nil ||
		!strings.Contains(err.Error(), "does not match the computed order") {
		t.Fatalf("fallback order drift must fail, got %v", err)
	}
	inOrder := map[string][]config.PoolEntry{
		"1": {{Slug: "hero-a"}, {Slug: "hero-c"}, {Slug: "hero-b"}},
	}
	if err := validateRenderedGates(valid, roles, inOrder); err != nil {
		t.Fatalf("faithful render must validate, got %v", err)
	}
}
