import { test } from 'node:test';
import assert from 'node:assert/strict';
import PickerSubset from './picker-subset.js';
import PickerScore from './picker-score.js';

// fixture cloned from picker-score.test.mjs baseGen, trimmed to the subset
// surface: 12 roster heroes, 4 pool heroes, echo seated at 2 roles, plus the
// prose/heroPos/trend arrays the swap slices and a fallbackOrder table with
// granted and ungranted entries per role
const ROSTER = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot',
  'golf', 'hotel', 'india', 'juliet', 'kilo', 'lima'];
const POP = [0.5, 0.4, 0.3, 0.2, 0.1, 0.6, 0.0, 0.7, 0.0, 0.45, 0.25, 0.35];
const POOL = [0, 4, 6, 7]; // alpha pos1, echo pos2+3, golf pos3 flex, hotel pos3

function row(fills) {
  return ROSTER.map((_, i) => i + ':' + (fills[i] !== undefined ? fills[i] : 0.5) + ':0').join(',');
}
function baseGen() {
  return {
    date: '2026-09-24', patch: 't', rosterCount: 12,
    slugs: ROSTER, names: ROSTER.map(s => s[0].toUpperCase() + s.slice(1)), icons: ROSTER,
    pop: POP, poolIdx: POOL.slice(),
    entries: [
      { roles: ['1'], tier: { '1': 'dedicated' } },
      { roles: ['2', '3'], tier: { '2': 'dedicated', '3': 'dedicated' } },
      { roles: ['3'], tier: { '3': 'flex' } },
      { roles: ['3'], tier: { '3': 'dedicated' } },
    ],
    prose: [{ identity: 'pa' }, { identity: 'pe' }, { identity: 'pg' }, { identity: 'ph' }],
    mu: [row({ 3: 0.7, 7: 0.3 }), row({ 3: 0.8 }), row({ 5: 0.6 }), row({})],
    syn: [row({ 1: 0.9 }), row({ 2: 0.6 }), row({ 0: 0.4 }), row({ 4: 0.55 })],
    prior: [0.5, 0.4, 0.3, 0.4],
    heroPos: [[[1, 1, 0.5]], [[2, 0.7, 0.5]], [[3, 1, 0.5]], [[3, 0.8, 0.5]]],
    trend: [null, [0.5, 0.1], null, [-0.2, 0.05]],
    weights: { knownMu: 1.0, synByRole: { '1': 0.7, '2': 0.2, '3': 0.3, '4': 1, '5': 1 }, prior: 0.5, genericFit: 0.4, exposure: 0.5, flexibility: 0.3 },
    scoreConsts: { enemySlots: 5, allySlots: 4, midPct: 0.5, flexCap: 50, flexHalf: 2 },
    meta: { bracket: 'X', window: 'w', perHeroSource: {} },
    gates: {
      roleNotes: {},
      fallbackOrder: { '1': ['alpha', 'echo'], '2': ['echo'], '3': ['echo', 'golf', 'hotel'] },
      rules: [], autogenerated: [], gateDeltas: { bonus: 0.25, penalty: -0.25 },
      aoeClearHeroes: ['charlie', 'delta'],
    },
  };
}

const SUB = PickerSubset;
const SCORE = PickerScore;
const EMPTY = { allies: [], enemies: [], banned: [], role: '3' };
const close = (a, b) => assert.ok(Math.abs(a - b) < 1e-9, 'expected ' + b + ', got ' + a);
// grant view: alpha keeps 1, echo drops 3 keeps 2, golf keeps 3, hotel fully
// dropped (its pair names a role it does not play), plus 2 stale pairs
const GRANT = [
  { slug: 'alpha', role: '1' },
  { slug: 'echo', role: '2' },
  { slug: 'golf', role: '3' },
  { slug: 'ghost', role: '1' },
  { slug: 'hotel', role: '9' },
];
// keeps the first and last pool positions, so slicing cannot read as truncation
const ENDS = [{ slug: 'alpha', role: '1' }, { slug: 'hotel', role: '3' }];
const PARALLEL = ['poolIdx', 'entries', 'prose', 'mu', 'syn', 'prior', 'heroPos', 'trend'];

test('kept is a subsequence of the pool, all parallel arrays sliced together', () => {
  const g = baseGen();
  const restore = SUB.apply(g, ENDS);
  PARALLEL.forEach(k => assert.equal(g[k].length, 2, k + ' not sliced to the kept count'));
  assert.deepEqual(g.poolIdx, [0, 7]);
  assert.deepEqual(g.prose, [{ identity: 'pa' }, { identity: 'ph' }]);
  assert.deepEqual(g.mu, [baseGen().mu[0], baseGen().mu[3]]);
  assert.deepEqual(g.syn, [baseGen().syn[0], baseGen().syn[3]]);
  assert.deepEqual(g.prior, [0.5, 0.4]);
  assert.deepEqual(g.heroPos, [[[1, 1, 0.5]], [[3, 0.8, 0.5]]]);
  assert.deepEqual(g.trend, [null, [-0.2, 0.05]]);
  // entries align with poolIdx: alpha's and hotel's granted seats, in order
  assert.deepEqual(g.entries, [
    { roles: ['1'], tier: { '1': 'dedicated' } },
    { roles: ['3'], tier: { '3': 'dedicated' } },
  ]);
  restore();
});

test('tier map and roles intersect, multi-role hero keeps only the granted seat', () => {
  const g = baseGen();
  const restore = SUB.apply(g, GRANT);
  assert.deepEqual(g.poolIdx, [0, 4, 6]);
  // echo loses seat 3, keeps 2 with its tier, golf keeps its flex tier
  assert.deepEqual(g.entries[1], { roles: ['2'], tier: { '2': 'dedicated' } });
  assert.deepEqual(g.entries[2], { roles: ['3'], tier: { '3': 'flex' } });
  restore();
});

test('fallbackOrder per role carries only granted slugs', () => {
  const r = SUB.computeSubset(baseGen(), GRANT);
  // echo sits in the 1 and 3 lists but granted only 2, hotel granted nothing
  assert.deepEqual(r.fallbackOrder, { '1': ['alpha'], '2': ['echo'], '3': ['golf'] });
});

test('unknown slug and role pairs are ignored without error', () => {
  const r = SUB.computeSubset(baseGen(), [{ slug: 'ghost', role: '1' }, { slug: 'hotel', role: '9' }]);
  assert.deepEqual(r.kept, []);
  assert.deepEqual(r.entries, []);
  assert.deepEqual(r.fallbackOrder, { '1': [], '2': [], '3': [] });
});

test('computeSubset is pure, G untouched', () => {
  const g = baseGen();
  const frozen = structuredClone(g);
  SUB.computeSubset(g, GRANT);
  assert.deepEqual(g, frozen);
});

test('apply then restore round-trips every swapped array and fallbackOrder', () => {
  const g = baseGen();
  const frozen = structuredClone(g);
  SCORE.rankRole(g, EMPTY, '3'); // warm the memo cache before the swap too
  SUB.apply(g, GRANT)();
  SUB.apply(g, ENDS)();
  SUB.apply(g, [])();
  assert.deepEqual(g, frozen);
});

test('apply drops the score memo cache, scores stay identical across the swap', () => {
  const g = baseGen();
  const before = SCORE.scoreCandidate(g, EMPTY, '3', 7).score;
  assert.ok(g.__psCache, 'scoring must populate the memo cache first');
  const restore = SUB.apply(g, ENDS);
  assert.ok(!('__psCache' in g), 'apply must drop the memo cache');
  // hotel slides from pool position 3 to 1 under the slice, a stale cache
  // would score it on echo's parsed rows
  close(SCORE.scoreCandidate(g, EMPTY, '3', 7).score, before);
  restore();
  assert.ok(!('__psCache' in g), 'restore must drop the memo cache again');
  close(SCORE.scoreCandidate(g, EMPTY, '3', 7).score, before);
});

test('with a subset applied rankRole returns members only, non-members throw', () => {
  const g = baseGen();
  const restore = SUB.apply(g, GRANT);
  // role 3 field: golf only, echo lost the seat and hotel is gone entirely
  assert.deepEqual(SCORE.rankRole(g, EMPTY, '3').map(r => r.idx), [6]);
  assert.deepEqual(SCORE.rankRole(g, EMPTY, '2').map(r => r.idx), [4]);
  assert.throws(() => SCORE.scoreCandidate(g, EMPTY, '3', 7), /not in pool/);
  restore();
  assert.deepEqual(SCORE.rankRole(g, EMPTY, '3').map(r => r.idx).sort((a, b) => a - b), [4, 6, 7]);
});

test('a subset matching nothing empties the view and still round-trips', () => {
  const g = baseGen();
  const frozen = structuredClone(g);
  const restore = SUB.apply(g, [{ slug: 'ghost', role: '1' }]);
  PARALLEL.forEach(k => assert.equal(g[k].length, 0, k));
  assert.deepEqual(SCORE.rankRole(g, EMPTY, '3'), []);
  restore();
  assert.deepEqual(g, frozen);
});
