import { test } from 'node:test';
import assert from 'node:assert/strict';
import PickerScore from './picker-score.js';

// tiny hand-computed fixture: 12 roster heroes, 4 pool heroes
// roster 0 alpha, 1 bravo, 2 charlie, 3 delta, 4 echo, 5 foxtrot,
// 6 golf, 7 hotel, 8 india, 9 juliet, 10 kilo, 11 lima
const ROSTER = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot',
  'golf', 'hotel', 'india', 'juliet', 'kilo', 'lima'];
const POP = [0.5, 0.4, 0.3, 0.2, 0.1, 0.6, 0.0, 0.7, 0.0, 0.45, 0.25, 0.35];
const POOL = [0, 4, 6, 7]; // alpha pos1, echo pos2+3, golf pos3 flex, hotel pos3

function row(fills) {
  return ROSTER.map((_, i) => i + ':' + (fills[i] !== undefined ? fills[i] : 0.5) + ':0').join(',');
}
function baseGen() {
  return {
    date: '2026-09-24', patch: 't', rosterCount: 12,
    slugs: ROSTER, names: ROSTER.map(s => s[0].toUpperCase() + s.slice(1)), icons: ROSTER,
    pop: POP, poolIdx: POOL,
    entries: [
      { roles: ['1'], tier: { '1': 'dedicated' } },
      { roles: ['2', '3'], tier: { '2': 'dedicated', '3': 'dedicated' } },
      { roles: ['3'], tier: { '3': 'flex' } },
      { roles: ['3'], tier: { '3': 'dedicated' } },
    ],
    mu: [row({ 3: 0.7, 7: 0.3 }), row({ 3: 0.8 }), row({ 5: 0.6 }), row({})],
    syn: [row({ 1: 0.9 }), row({ 2: 0.6 }), row({ 0: 0.4 }), row({ 4: 0.55 })],
    prior: [0.5, 0.4, 0.3, 0.4],
    weights: { knownMu: 1.0, synByRole: { '1': 0.7, '2': 0.2, '3': 0.3, '4': 1, '5': 1 }, prior: 0.5, genericFit: 0.4, exposure: 0.5, flexibility: 0.3 },
    scoreConsts: { enemySlots: 5, allySlots: 4, midPct: 0.5, flexCap: 50, flexHalf: 2 },
    meta: { bracket: 'X', window: 'w', perHeroSource: {} },
    gates: {
      roleNotes: {}, fallbackOrder: {},
      rules: [{ id: 'alpha-veto', target: 'alpha', roles: ['1'],
        when: [{ kind: 'enemyVisibleAny', heroes: ['delta'] }],
        action: 'hard_gate', note: 'veto alpha' }],
      autogenerated: [],
      gateDeltas: { bonus: 0.25, penalty: -0.25 },
      aoeClearHeroes: ['charlie', 'delta'],
    },
  };
}
const PS = PickerScore;
const close = (a, b, eps = 1e-9) => assert.ok(Math.abs(a - b) < eps, 'expected ' + b + ', got ' + a);
const withRules = rules => { const g = baseGen(); g.gates.rules = rules; return g; };
const EMPTY = { allies: [], enemies: [], banned: [], role: '1' };
// run one rule against its own target, report whether it fired
const fires = (rule, state) => {
  const g = withRules([rule]);
  const idx = g.slugs.indexOf(rule.target);
  return PS.scoreCandidate(g, state, rule.roles[0], idx).firedRuleIds.includes(rule.id);
};

test('payload without scoreConsts fails loud', () => {
  const g = baseGen();
  delete g.scoreConsts;
  assert.throws(() => PS.scoreCandidate(g, EMPTY, '1', 0), /missing scoreConsts/);
});

test('packed string parse, empty and missing conf', () => {
  assert.deepEqual(PS.parsePacked(''), []);
  assert.deepEqual(PS.parsePacked('3:0.1234:1,7:0.5:0'),
    [{ idx: 3, pct: 0.1234, conf: 1 }, { idx: 7, pct: 0.5, conf: 0 }]);
  assert.deepEqual(PS.parsePacked('5:0.25,'), [{ idx: 5, pct: 0.25, conf: 0 }]);
});

test('payload without synByRole fails loud', () => {
  const st = { allies: [1], enemies: [], banned: [], role: '1' };
  const gone = baseGen();
  delete gone.weights.synByRole;
  assert.throws(() => PS.scoreCandidate(gone, st, '1', 0), /missing synByRole/);
  const holed = baseGen();
  holed.weights.synByRole = { '1': 0.7 };
  assert.throws(() => PS.scoreCandidate(holed, st, '2', 0), /synByRole has no role 2/);
});

test('syn term scales by the role being picked', () => {
  const g = baseGen();
  const st = { allies: [1, 2], enemies: [3, 4, 7], banned: [5] };
  // knownMu = (delta .7, echo .5, hotel .3) / 3 = 0.5, knownSyn = (bravo .9, charlie .5) / 2 = 0.7
  const byRole = {};
  ['1', '2', '3', '4', '5'].forEach(r => { byRole[r] = PS.scoreCandidate(g, st, r, 0).score; });
  const w = g.weights.synByRole;
  close(byRole['4'] - byRole['1'], (w['4'] - w['1']) * (2 / 5) * 0.7);
  close(byRole['2'] - byRole['1'], (w['2'] - w['1']) * (2 / 5) * 0.7);
  close(byRole['5'] - byRole['4'], 0);
  // full pin at role 4: exposure and flexibility are 0 in this state, no gate delta
  close(byRole['4'], 1.0 * (3 / 5) * 0.5 + w['4'] * (2 / 5) * 0.7 + 0.5 * 0.5 + 0.4 * (2 / 4) * 0.5);
  // with no allies picked the term is zero for every role
  close(PS.scoreCandidate(g, EMPTY, '4', 0).score, PS.scoreCandidate(g, EMPTY, '1', 0).score);
});

test('first pick, a=0 k=0, expectation only', () => {
  const g = baseGen();
  const r = PS.scoreCandidate(g, EMPTY, '1', 0);
  assert.equal(r.terms.knownMu, 0);
  assert.equal(r.terms.knownSyn, 0);
  close(r.terms.prior, 0.5);
  // unseen allies = 1..11, syn 0.9 at bravo (pop 0.4), 0.5 elsewhere, pop sum 3.35
  const fit = (0.4 * 0.9 + 2.95 * 0.5) / 3.35;
  close(r.terms.genericFit, fit);
  // unseen enemies same set, overhang max(0, 0.5 - 0.5) = 0 except hotel 0.7 pop: 0.2
  close(r.terms.exposure, (0.7 * 0.2) / 3.35);
  // flex enemies all 11: mu 0.7 at delta, 0.3 at hotel, 0.5 elsewhere, population var (0.04 + 0.04)/11
  close(r.terms.flexibility, -Math.sqrt(0.08 / 11) / 2);
  close(r.terms.gateDelta, 0);
  assert.equal(r.hardGated, false);
  // (4-0)/4 = 1, (5-0)/5 = 1, so full weights on the expectation terms
  close(r.score, 0.5 * 0.5 + 0.4 * fit - 0.5 * ((0.7 * 0.2) / 3.35) + 0.3 * (-Math.sqrt(0.08 / 11) / 2));
});

test('mid draft, a=2 k=3, hard gate fires with no delta', () => {
  const g = baseGen();
  const st = { allies: [1, 2], enemies: [3, 4, 7], banned: [5], role: '1' };
  const r = PS.scoreCandidate(g, st, '1', 0);
  // knownMu = (alpha vs delta .7, echo .5, hotel .3) / 3
  close(r.terms.knownMu, 0.5);
  // knownSyn = (bravo .9, charlie .5) / 2
  close(r.terms.knownSyn, 0.7);
  close(r.terms.prior, 0.5);
  // unseen allies golf, india, juliet, kilo, lima, syn all 0.5, pop weight 1.05
  close(r.terms.genericFit, 0.5);
  // unseen enemies same set, all mu 0.5, no overhang
  close(r.terms.exposure, 0);
  // flex enemies by pop: juliet .45, lima .35, kilo .25, golf 0, india 0, all mu 0.5
  close(r.terms.flexibility, 0);
  // alpha-veto: delta is visible, hard gate carries no delta
  assert.equal(r.hardGated, true);
  assert.deepEqual(r.firedRuleIds, ['alpha-veto']);
  assert.deepEqual(r.notes, ['veto alpha']);
  assert.equal(r.terms.gateDelta, 0);
  // (4-2)/4 = 0.5 still on genericFit, (5-3)/5 = 0.4 kills nothing here
  close(r.score, 1.0 * (3 / 5) * 0.5 + 0.7 * (2 / 5) * 0.7 + 0.5 * 0.5 + 0.4 * (2 / 4) * 0.5);
});

test('last pick, a=4 k=5, genericFit and exposure phases hit 0', () => {
  const g = baseGen();
  const st = { allies: [1, 2, 3, 5], enemies: [4, 7, 9, 10, 11], banned: [], role: '1' };
  const r = PS.scoreCandidate(g, st, '1', 0);
  // knownMu = (.5 + .3 + .5 + .5 + .5) / 5 vs echo, hotel, juliet, kilo, lima
  close(r.terms.knownMu, 0.46);
  // knownSyn = (.9 + .5 + .5 + .5) / 4 for bravo, charlie, delta, foxtrot
  close(r.terms.knownSyn, 0.6);
  close(r.terms.prior, 0.5);
  // unseen golf, india, both pop 0, total weight 0 falls back to plain mean
  close(r.terms.genericFit, 0.5);
  close(r.terms.exposure, 0);
  close(r.terms.flexibility, 0);
  // delta sits on our side, the veto checks enemies only
  assert.equal(r.hardGated, false);
  assert.equal(r.terms.gateDelta, 0);
  // (4-4)/4 = 0 and (5-5)/5 = 0 zero out the last two phases
  close(r.score, 1.0 * (5 / 5) * 0.46 + 0.7 * (4 / 5) * 0.6 + 0.5 * 0.5);
});

test('bonus and penalty shift score by exact gateDeltas', () => {
  const st = { allies: [], enemies: [3], banned: [], role: '2' };
  const rule = action => ({ id: action, target: 'echo', roles: ['2'],
    when: [{ kind: 'enemyVisibleAny', heroes: ['delta'] }], action, note: 'x' });
  const plain = withRules([]);
  const base = PS.scoreCandidate(plain, st, '2', 4).score;
  const on = PS.scoreCandidate(withRules([rule('bonus')]), st, '2', 4);
  close(on.terms.gateDelta, 0.25);
  close(on.score - base, 0.25);
  const off = PS.scoreCandidate(withRules([rule('penalty')]), st, '2', 4);
  close(off.terms.gateDelta, -0.25);
  close(off.score - base, -0.25);
});

test('role scoping, rule for pos 4 silent at pos 5', () => {
  const g = withRules([{ id: 's1', target: 'alpha', roles: ['4'],
    when: [{ kind: 'enemyVisibleAny', heroes: ['delta'] }], action: 'bonus' }]);
  const st4 = { allies: [], enemies: [3], banned: [], role: '4' };
  close(PS.scoreCandidate(g, st4, '4', 0).terms.gateDelta, 0.25);
  const st5 = { allies: [], enemies: [3], banned: [], role: '5' };
  close(PS.scoreCandidate(g, st5, '5', 0).terms.gateDelta, 0);
});

test('condition vocabulary, visible all/any/none, ally, counts, aoe, note_only', () => {
  const all = { id: 'v1', target: 'alpha', roles: ['1'],
    when: [{ kind: 'enemyVisible', heroes: ['delta', 'echo'] }], action: 'bonus' };
  assert.equal(fires(all, { allies: [], enemies: [3, 4], banned: [], role: '1' }), true);
  assert.equal(fires(all, { allies: [], enemies: [3], banned: [], role: '1' }), false);
  const none = { id: 'v2', target: 'alpha', roles: ['1'],
    when: [{ kind: 'enemyVisibleNone', heroes: ['delta'] }], action: 'bonus' };
  assert.equal(fires(none, { allies: [], enemies: [7], banned: [], role: '1' }), true);
  assert.equal(fires(none, { allies: [], enemies: [3], banned: [], role: '1' }), false);
  const ally = { id: 'v3', target: 'alpha', roles: ['1'],
    when: [{ kind: 'allyVisibleAny', heroes: ['bravo'] }], action: 'bonus' };
  assert.equal(fires(ally, { allies: [1], enemies: [], banned: [], role: '1' }), true);
  assert.equal(fires(ally, { allies: [2], enemies: [], banned: [], role: '1' }), false);
  const ecmin = { id: 'v4', target: 'alpha', roles: ['1'],
    when: [{ kind: 'enemyCountMin', count: 3 }], action: 'bonus' };
  assert.equal(fires(ecmin, { allies: [], enemies: [3, 4, 7], banned: [], role: '1' }), true);
  assert.equal(fires(ecmin, { allies: [], enemies: [3, 4], banned: [], role: '1' }), false);
  const ecmax = { id: 'v5', target: 'alpha', roles: ['1'],
    when: [{ kind: 'enemyCountMax', count: 1 }], action: 'bonus' };
  assert.equal(fires(ecmax, { allies: [], enemies: [3], banned: [], role: '1' }), true);
  assert.equal(fires(ecmax, { allies: [], enemies: [3, 4], banned: [], role: '1' }), false);
  const countMin = { id: 'c2', target: 'hotel', roles: ['1'],
    when: [{ kind: 'enemyVisibleAnyCountMin', heroes: ['delta', 'echo'], count: 2 }], action: 'bonus' };
  assert.equal(fires(countMin, { allies: [], enemies: [3], banned: [], role: '1' }), false);
  assert.equal(fires(countMin, { allies: [], enemies: [3, 4], banned: [], role: '1' }), true);
  const only = { id: 'v6', target: 'alpha', roles: ['1'],
    when: [{ kind: 'enemyVisibleAny', heroes: ['delta'] }], action: 'note_only', note: 'heads up' };
  const r = PS.scoreCandidate(withRules([only]),
    { allies: [], enemies: [3], banned: [], role: '1' }, '1', 0);
  assert.deepEqual(r.notes, ['heads up']);
  assert.deepEqual(r.firedRuleIds, ['v6']);
  close(r.terms.gateDelta, 0);
  assert.equal(r.hardGated, false);
});

test('enemyAoEMax and enemyAoEMin count aoe clear enemies', () => {
  // fixture aoe list: charlie(2), delta(3)
  const maxRule = { id: 'am', target: 'hotel', roles: ['3'],
    when: [{ kind: 'enemyAoEMax', max: 1 }], action: 'bonus' };
  assert.equal(fires(maxRule, { allies: [], enemies: [2, 4], banned: [], role: '3' }), true);
  assert.equal(fires(maxRule, { allies: [], enemies: [2, 3, 4], banned: [], role: '3' }), false);
  const minRule = { id: 'an', target: 'hotel', roles: ['3'],
    when: [{ kind: 'enemyAoEMin', min: 2 }], action: 'bonus' };
  assert.equal(fires(minRule, { allies: [], enemies: [2, 3], banned: [], role: '3' }), true);
  assert.equal(fires(minRule, { allies: [], enemies: [3], banned: [], role: '3' }), false);
});

test('minEnemyCount bounds by visible enemy count', () => {
  const mec = { id: 'm1', target: 'hotel', roles: ['3'],
    when: [{ kind: 'minEnemyCount', minEnemyCount: 2 }], action: 'bonus' };
  assert.equal(fires(mec, { allies: [], enemies: [3, 4], banned: [], role: '3' }), true);
  assert.equal(fires(mec, { allies: [], enemies: [3], banned: [], role: '3' }), false);
});

test('role-less rules are wildcards, autoseed rules fire in every role', () => {
  const g = withRules([{ id: 'w1', target: 'alpha',
    when: [{ kind: 'enemyVisibleAny', heroes: ['delta'] }], action: 'hard_gate', note: 'global veto' }]);
  const r = PS.scoreCandidate(g, { allies: [], enemies: [3], banned: [], role: '3' }, '3', 0);
  assert.equal(r.hardGated, true);
  assert.deepEqual(r.firedRuleIds, ['w1']);
});

test('omitted condition fields read go zero values, not undefined', () => {
  const countless = { id: 'z1', target: 'alpha', roles: ['1'],
    when: [{ kind: 'enemyCountMin' }], action: 'bonus' };
  assert.equal(fires(countless, EMPTY), true);
  const emptyHeroes = { id: 'z2', target: 'alpha', roles: ['1'],
    when: [{ kind: 'enemyVisible', heroes: [] }], action: 'bonus' };
  assert.equal(fires(emptyHeroes, EMPTY), false);
});

test('roleCandidatesGated reads the gated count of the role', () => {
  const g = withRules([
    { id: 'h1', target: 'echo', roles: ['3'],
      when: [{ kind: 'enemyVisibleAny', heroes: ['delta'] }], action: 'hard_gate', note: 'echo off' },
    { id: 'h2', target: 'hotel', roles: ['3'],
      when: [{ kind: 'roleCandidatesGated', count: 2 }], action: 'bonus', note: 'fallback open' },
    { id: 'h3', target: 'golf', roles: ['3'],
      when: [{ kind: 'enemyVisibleAny', heroes: ['delta'] }], action: 'hard_gate', note: 'golf off' },
  ]);
  // echo and golf both hard gated with delta visible, count 2 fires
  const st = { allies: [], enemies: [3], banned: [], role: '3' };
  close(PS.scoreCandidate(g, st, '3', 7).terms.gateDelta, 0.25);
  // empty board: nothing gated, count 0 stays under 2
  const calm = { allies: [], enemies: [], banned: [], role: '3' };
  close(PS.scoreCandidate(g, calm, '3', 7).terms.gateDelta, 0);
});

test('tie-break by roster index ascending, ranking deterministic', () => {
  const g = baseGen();
  g.rosterCount = 3;
  g.slugs = ['aa', 'bb', 'cc']; g.names = ['Aa', 'Bb', 'Cc']; g.icons = ['aa', 'bb', 'cc'];
  g.pop = [0.3, 0.3, 0.3]; g.poolIdx = [0, 1, 2];
  g.entries = [{ roles: ['1'], tier: { '1': 'dedicated' } },
    { roles: ['1'], tier: { '1': 'dedicated' } }, { roles: ['1'], tier: { '1': 'dedicated' } }];
  g.mu = ['0:0.5:0,1:0.5:0,2:0.5:0', '0:0.5:0,1:0.5:0,2:0.5:0', '0:0.5:0,1:0.5:0,2:0.5:0'];
  g.syn = g.mu;
  g.prior = [0.4, 0.4, 0.9];
  g.gates.rules = [];
  const ranked = PS.rankRole(g, EMPTY, '1');
  // cc wins on prior 0.9, aa and bb tie fully and order by idx
  assert.deepEqual(ranked.map(r => r.idx), [2, 0, 1]);
  assert.deepEqual(PS.rankRole(g, EMPTY, '1'), ranked);
});

test('rankRole filters by role and taken heroes, flags hard gates', () => {
  const g = baseGen();
  const empty = PS.rankRole(g, EMPTY, '3');
  assert.deepEqual(empty.map(r => r.idx).sort((a, b) => a - b), [4, 6, 7]);
  const mid = { allies: [1, 2], enemies: [3, 4, 7], banned: [5], role: '1' };
  const one = PS.rankRole(g, mid, '1');
  assert.deepEqual(one.map(r => r.idx), [0]);
  assert.equal(one[0].hardGated, true);
});
