(function () {
'use strict';

const G = window.PICKER_GEN;
const PS = window.PickerScore;

const UI = {
  iconBase: 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/',
  teamSize: 5,
  banSlots: 16,
  nearZero: 0.005,
  acLimit: 40,
  termOrder: ['knownMu', 'knownSyn', 'prior', 'genericFit', 'exposure', 'flexibility', 'gateDelta'],
  termLabels: {
    knownMu: 'known mu', knownSyn: 'known syn', prior: 'prior', genericFit: 'generic fit',
    exposure: 'exposure', flexibility: 'flex', gateDelta: 'gate',
  },
};

const state = {
  allies: Array(UI.teamSize).fill(-1),
  enemies: Array(UI.teamSize).fill(-1),
  bans: Array(UI.banSlots).fill(-1),
  role: G.roles[0].id,
};
let target = { team: 'allies', slot: 0 };
let lastRows = [];

const $ = id => document.getElementById(id);
const el = (tag, cls, text) => {
  const n = document.createElement(tag);
  if (tag === 'button') n.type = 'button';
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
};

const rules = ((G.gates && G.gates.rules) || []).concat((G.gates && G.gates.autogenerated) || []);
const ruleMap = {};
rules.forEach(r => { ruleMap[r.id] = r; });

const snap = () => ({
  allies: state.allies.filter(i => i >= 0),
  enemies: state.enemies.filter(i => i >= 0),
  banned: state.bans.filter(i => i >= 0),
  role: state.role,
});
const takenSet = () => new Set(state.allies.concat(state.enemies, state.bans).filter(i => i >= 0));

function heroBadge(idx) {
  const wrap = el('span');
  const img = document.createElement('img');
  img.className = 'hicon';
  img.src = UI.iconBase + G.icons[idx] + '.png';
  img.alt = G.names[idx];
  img.onerror = () => {
    const s = el('span', 'hinit', G.names[idx].slice(0, 2).toUpperCase());
    img.replaceWith(s);
  };
  wrap.appendChild(img);
  return wrap;
}

function renderHeader() {
  const box = $('metaChips');
  box.textContent = '';
  const chip = (text, cls) => box.appendChild(el('span', 'tag' + (cls ? ' ' + cls : ''), text));
  if (G.patch) chip(G.patch);
  if (G.date) chip('data ' + G.date);
  if (G.meta && G.meta.bracket) chip(G.meta.bracket);
  if (G.meta && G.meta.window) chip(G.meta.window);
  const srcMap = (G.meta && G.meta.perHeroSource) || {};
  const fb = G.poolIdx.filter(idx => srcMap[G.slugs[idx]] !== 'stratz').length;
  if (fb === 0) chip('stratz', 'prov');
  else chip(fb + ' of ' + G.poolIdx.length + ' pool heroes off stratz', 'warn');
}

function renderRoles() {
  const seg = $('roleSel');
  seg.textContent = '';
  G.roles.forEach(r => {
    const b = el('button', 'segbtn' + (state.role === r.id ? ' on' : ''), r.label);
    b.onclick = () => {
      state.role = r.id; render();
      seg.children[G.roles.findIndex(x => x.id === r.id)].focus();
    };
    seg.appendChild(b);
  });
}

const firstEmpty = (team, from) => {
  for (let c = 0; c < state[team].length; c++) {
    const i = ((from || 0) + c) % state[team].length;
    if (state[team][i] < 0) return i;
  }
  return -1;
};
const behindSide = () => {
  const s = snap();
  return s.allies.length <= s.enemies.length ? 'allies' : 'enemies';
};
const boardFull = () => firstEmpty('allies') < 0 && firstEmpty('enemies') < 0 && firstEmpty('bans') < 0;

function retarget(prefer) {
  const other = t => (t === 'allies' ? 'enemies' : 'allies');
  const lead = prefer || behindSide();
  const chain = prefer === 'bans' ? ['bans', behindSide(), other(behindSide())] : [lead, other(lead), 'bans'];
  for (let c = 0; c < chain.length; c++) {
    const team = chain[c];
    const at = team === 'bans' ? firstEmpty('bans', target.team === 'bans' ? target.slot + 1 : 0) : firstEmpty(team);
    if (at >= 0) { target = { team: team, slot: at }; return; }
  }
}

function aimAt(team, slot) {
  if (state[team][slot] < 0) target = { team: team, slot: slot };
  else retarget(team);
}

const teamNames = { allies: 'our pick', enemies: 'enemy pick', bans: 'ban' };

function renderAim() {
  const chip = $('aimChip');
  chip.textContent = '';
  chip.className = 'aimchip';
  if (boardFull()) { chip.classList.add('full'); chip.textContent = 'board full'; return; }
  chip.classList.add(target.team);
  chip.textContent = teamNames[target.team] + ': slot ' + (target.slot + 1);
}

function renderSlots(container, slots, team) {
  container.textContent = '';
  const side = team === 'allies' ? 'our pick' : 'enemy pick';
  slots.forEach((idx, i) => {
    const aimed = target.team === team && target.slot === i && idx < 0;
    const d = el('button', 'slot' + (idx >= 0 ? ' filled' : '') + (aimed ? ' next' : ''));
    if (idx >= 0) {
      d.appendChild(heroBadge(idx));
      d.appendChild(el('span', 'slotname', G.names[idx]));
      d.setAttribute('aria-label', G.names[idx] + ' on ' + side + ', enter to clear');
      d.onclick = () => {
        slots[i] = -1;
        if (state[target.team][target.slot] >= 0) aimAt(team, i);
        render();
        container.children[i].focus();
      };
    } else {
      d.appendChild(el('span', 'plus', '+'));
      d.appendChild(el('span', 'slotname dim', side + ' ' + (i + 1)));
      d.setAttribute('aria-label', 'empty ' + side + ' slot ' + (i + 1) + ', enter to aim the search here');
      d.onclick = () => { aimAt(team, i); render(); $('search').focus(); };
    }
    container.appendChild(d);
  });
}

function renderBanStrip() {
  const box = $('bans');
  box.textContent = '';
  const n = state.bans.filter(i => i >= 0).length;
  box.appendChild(el('span', 'dim', 'bans ' + n + '/' + UI.banSlots));
  state.bans.forEach((idx, i) => {
    const aimed = target.team === 'bans' && target.slot === i && idx < 0;
    const d = el('button', 'banslot' + (idx >= 0 ? ' filled' : '') + (aimed ? ' next' : ''));
    if (idx >= 0) {
      d.appendChild(heroBadge(idx));
      d.appendChild(el('span', null, G.names[idx]));
      d.setAttribute('aria-label', G.names[idx] + ' banned, enter to remove ban');
      d.onclick = () => {
        state.bans[i] = -1;
        if (state[target.team][target.slot] >= 0) aimAt('bans', i);
        render();
        box.querySelectorAll('.banslot')[i].focus();
      };
    } else {
      d.appendChild(el('span', 'plus', '+'));
      d.setAttribute('aria-label', 'empty ban slot ' + (i + 1) + ', enter to aim the search here');
      d.onclick = () => { aimAt('bans', i); render(); $('search').focus(); };
    }
    box.appendChild(d);
  });
}

const slugIdx = {};
G.slugs.forEach((s, i) => { slugIdx[s] = i; });

function poolGroups() {
  return G.roles.map(r => {
    const idxs = [];
    (G.gates.fallbackOrder[r.id] || []).forEach(slug => {
      const idx = slugIdx[slug];
      if (idx !== undefined) idxs.push(idx);
    });
    for (let pi = 0; pi < G.poolIdx.length; pi++) {
      const entry = G.entries[pi] || { roles: [] };
      if (!idxs.includes(G.poolIdx[pi]) && entry.roles.includes(r.id)) idxs.push(G.poolIdx[pi]);
    }
    return { role: r, idxs: idxs };
  });
}
const flatPool = () => poolGroups().reduce((flat, g) => {
  g.idxs.forEach(idx => { if (!flat.includes(idx)) flat.push(idx); });
  return flat;
}, []);
let poolOrder = flatPool();
function refreshPoolView() {
  if (!ac) return;
  poolOrder = flatPool();
  ac.setPoolOrder(poolOrder);
  render();
}

function legendChip(idx, taken) {
  const c = el('span', 'herochip' + (taken.has(idx) ? ' out' : ''));
  c.appendChild(heroBadge(idx));
  c.appendChild(el('span', null, G.names[idx]));
  return c;
}

function renderLegend() {
  const box = $('legend');
  box.textContent = '';
  const taken = takenSet();
  poolGroups().forEach(g => {
    box.appendChild(el('div', 'legendhead', g.role.label));
    const grp = el('div', 'legendgrp');
    g.idxs.forEach(idx => grp.appendChild(legendChip(idx, taken)));
    box.appendChild(grp);
  });
}

function pick(idx) {
  if (takenSet().has(idx)) return;
  if (boardFull()) return;
  if (state[target.team][target.slot] >= 0) retarget(target.team);
  state[target.team][target.slot] = idx;
  ac.clearAndHide();
  retarget(target.team === 'bans' ? 'bans' : undefined);
  render();
}

function renderPhase() {
  const s = snap();
  const box = $('phase');
  box.textContent = '';
  const total = 2 * UI.teamSize;
  const at = Math.min(s.allies.length + s.enemies.length + 1, total);
  box.appendChild(el('span', 'turn', 'pick ' + at + '/' + total
    + (at < total ? ', ' + (s.allies.length <= s.enemies.length ? 'our pick' : 'enemy pick incoming') : '')));
  box.appendChild(el('span', 'dim', 'allies ' + s.allies.length + '/' + UI.teamSize));
  box.appendChild(el('span', 'dim', 'enemies ' + s.enemies.length + '/' + UI.teamSize));
  box.appendChild(el('span', 'dim', 'bans ' + s.banned.length + '/' + UI.banSlots));
}

function computeRows() {
  const s = snap();
  const rows = PS.rankRole(G, s, state.role);
  if (rows.length) return { rows: rows, widened: false };
  const taken = takenSet();
  const wide = [];
  G.poolIdx.forEach(idx => {
    if (!taken.has(idx)) wide.push(Object.assign({ idx }, PS.scoreCandidate(G, s, state.role, idx)));
  });
  wide.sort((x, y) => y.score - x.score || x.idx - y.idx);
  return { rows: wide, widened: true };
}

function bannerLines(rows, widened) {
  const s = snap();
  const lines = [];
  if (s.allies.length + s.enemies.length === 0) {
    lines.push('empty board: ranking is expectation driven, prior, generic fit, and flexibility lead until picks land');
  }
  if (widened) {
    lines.push('no untaken candidates left for the selected role, ranking widened to every untaken hero in the active pool with role mismatch chips');
  } else if (rows.length && rows.every(r => r.hardGated)) {
    lines.push('every role candidate is gated, ranking shows the least bad with veto notes');
  }
  return lines;
}

function renderBanner(lines) {
  const box = $('banner');
  box.textContent = '';
  lines.forEach(t => box.appendChild(el('div', null, t)));
}

function lowConf(pos) {
  const all = PS.parsePacked(G.mu[pos]).concat(PS.parsePacked(G.syn[pos]));
  const low = all.filter(r => r.conf === 2).length;
  return 2 * low > all.length;
}

function toggleProse(row, pos) {
  const open = row.nextElementSibling;
  if (open && open.classList.contains('fw')) {
    open.remove();
    row.setAttribute('aria-expanded', 'false');
    return;
  }
  document.querySelectorAll('#results .fw').forEach(n => n.remove());
  document.querySelectorAll('#results .rrow[aria-expanded="true"]')
    .forEach(n => n.setAttribute('aria-expanded', 'false'));
  const p = (G.prose || [])[pos];
  const panel = el('div', 'fw');
  const r = lastRows.find(x => x.idx === G.poolIdx[pos]);
  if (r && r.notes.length) {
    r.notes.forEach(n => {
      const line = el('div', 'fwline');
      const rule = r.firedRuleIds.map(id => ruleMap[id]).find(x => x && x.note === n);
      if (rule && rule.action === 'hard_gate') line.appendChild(el('span', 'tag veto', 'veto'));
      line.appendChild(document.createTextNode(n));
      panel.appendChild(line);
    });
  }
  const sNow = snap();
  if (sNow.allies.length) {
    const synRow = PS.parsePacked(G.syn[pos]);
    let best = null;
    sNow.allies.forEach(i => {
      const hit = synRow.find(x => x.idx === i);
      if (hit && (!best || hit.pct > best.pct)) best = hit;
    });
    if (best && best.pct > 0.5) {
      panel.appendChild(el('div', 'fwline', 'lanes best with ' + G.names[best.idx]));
    }
  }
  if (!p) {
    if (!panel.childNodes.length) panel.appendChild(el('div', 'note', 'no framework prose emitted for this hero'));
    row.after(panel);
    row.setAttribute('aria-expanded', 'true');
    return;
  }
  const timings = (p.timings || []).map(t => t[0] + ' by ' + t[1]).join(', ');
  const mech = m => ((p.mechanics || []).filter(x => x[0] === m).map(x => x[1]).join('. '));
  [['identity', p.identity], ['why', p.why], ['how', p.how], ['when', p.when],
   ['build', p.build], ['timings', timings], ['tech', (p.tech || []).join('. ')],
   ['mechanics', mech('tip')], ['counters', mech('counter')]]
    .forEach(([k, v]) => {
      if (!v) return;
      const line = el('div', 'fwline');
      line.appendChild(el('span', 'fwk', k));
      line.appendChild(el('span', null, v));
      panel.appendChild(line);
    });
  row.after(panel);
  row.setAttribute('aria-expanded', 'true');
}

function renderResults(rows, widened) {
  const box = $('results');
  box.textContent = '';
  lastRows = rows;
  box.classList.toggle('grey', rows.length > 0 && rows.every(r => r.hardGated));
  const srcMap = (G.meta && G.meta.perHeroSource) || {};
  const fmt = v => (v > 0 ? '+' : '') + v.toFixed(2);
  const vclass = v => v > UI.nearZero ? 'pos' : (v < -UI.nearZero ? 'neg' : 'zero');

  const head = el('div', 'rhead');
  head.appendChild(el('span', 'tl', ''));
  head.appendChild(el('span', 'tl', ''));
  head.appendChild(el('span', 'tl', 'hero'));
  UI.termOrder.forEach(t => head.appendChild(el('span', 'tl th', UI.termLabels[t])));
  head.appendChild(el('span', 'tl scoreh', 'score'));
  box.appendChild(head);

  rows.forEach((r, i) => {
    const row = el('button', 'rrow');
    row.setAttribute('aria-expanded', 'false');
    row.appendChild(el('span', 'rank', String(i + 1)));
    row.appendChild(heroBadge(r.idx));
    const mid = el('div', 'rmid');

    const chips = el('div', 'chipline');
    chips.appendChild(el('span', 'rname', G.names[r.idx]));
    const pos = G.poolIdx.indexOf(r.idx);
    const entry = G.entries[pos] || { roles: [], tier: {} };
    const tier = entry.tier && entry.tier[state.role];
    if (tier && tier !== 'dedicated') chips.appendChild(el('span', 'tag flex', tier));
    const stats = (G.heroPos || [])[pos];
    if (stats && stats.length) {
      const top = stats[0];
      const cls = String(top[0]) !== state.role ? ' tag mismatch' : '';
      chips.appendChild(el('span', 'tag pos' + cls,
        'pos ' + top[0] + ' ' + Math.round(top[1] * 100) + '%'));
    }
    const tr = (G.trend || [])[pos];
    if (tr) {
      const chip = el('span', 'tag tr ' + (tr[0] >= 0 ? 'tup' : 'tdn'),
        'wr ' + (tr[0] >= 0 ? '+' : '') + tr[0].toFixed(1));
      chip.title = 'pick share ' + (tr[1] >= 0 ? '+' : '') + tr[1].toFixed(2) + 'pp';
      chips.appendChild(chip);
    }
    if (widened && !entry.roles.includes(state.role)) {
      chips.appendChild(el('span', 'tag mismatch', 'role mismatch'));
    }
    if (r.hardGated) chips.appendChild(el('span', 'tag veto', 'veto'));
    const src = srcMap[G.slugs[r.idx]];
    chips.appendChild(el('span', 'tag' + (src === 'stratz' ? ' prov' : ' warn'), src || 'no source'));
    if (lowConf(pos)) {
      const dot = el('span', 'dot');
      dot.title = 'low confidence data rows dominate';
      chips.appendChild(dot);
    }
    mid.appendChild(chips);
    row.appendChild(mid);

    UI.termOrder.forEach(t => {
      row.appendChild(el('span', 'tv ' + vclass(r.terms[t]), fmt(r.terms[t])));
    });
    row.appendChild(el('span', 'rscore ' + vclass(r.score), fmt(r.score)));
    box.appendChild(row);
    row.addEventListener('click', () => toggleProse(row, pos));
  });
}

function render() {
  const { rows, widened } = computeRows();
  renderHeader();
  renderAim();
  renderRoles();
  renderSlots($('allySlots'), state.allies, 'allies');
  renderSlots($('enemySlots'), state.enemies, 'enemies');
  renderBanStrip();
  renderLegend();
  renderPhase();
  renderBanner(bannerLines(rows, widened));
  renderResults(rows, widened);
  ac.refresh();
}

document.documentElement.style.setProperty('--rrow-cols',
  '2.2rem 2rem minmax(16rem, 1fr) repeat(' + UI.termOrder.length + ', 4.6rem) 4.6rem');

const ac = window.PickerSearch.mount({
  G: G,
  input: $('search'),
  list: $('acList'),
  badge: heroBadge,
  isTaken: takenSet,
  onPick: pick,
  limit: UI.acLimit,
  poolOrder: poolOrder,
});

(function seedShotState() {
  const q = new URLSearchParams(location.search);
  if (![...q.keys()].length) return;
  ['allies', 'enemies', 'bans'].forEach(team => {
    (q.get(team) || '').split(',').filter(Boolean).forEach(slug => {
      const idx = slugIdx[slug];
      const at = idx === undefined || takenSet().has(idx) ? -1 : firstEmpty(team);
      if (at >= 0) state[team][at] = idx;
    });
  });
  const role = q.get('role');
  if (role && G.roles.some(r => r.id === role)) state.role = role;
  const aim = (q.get('aim') || '').split(':');
  const slot = aim.length === 2 && ['allies', 'enemies', 'bans'].includes(aim[0])
    ? Number(aim[1]) - 1 : NaN;
  if (Number.isInteger(slot) && slot >= 0 && slot < state[aim[0]].length) aimAt(aim[0], slot);
})();
render();
if (window.PickerSubset) window.PickerSubset.boot({ G: G, onChange: refreshPoolView });
})();
