#Requires -Version 7
# Generates guide/guide-data-generated.js from the current matchup md
# tables. Filters to |dis%| >= threshold and packs rows as compact strings so
# the guide loads from file:// with no fetch. Runs via `make build-guide-data`.
# SUPERSEDED: the engine's emit guide owns this output now. The pool list below
# is the PREVIOUS 18-hero pool; this script stays only as the parity oracle for
# the Go port until the diff matches, then it retires. Do not extend it.
[CmdletBinding()]
param(
    [string] $Date = (Get-Date -Format 'yyyy-MM-dd'),
    [double] $Threshold = 1.5
)

$ErrorActionPreference = 'Stop'

$Config = @{
    Date      = $Date
    Threshold = $Threshold
    Pool      = @('lifestealer', 'spectre', 'tiny', 'lone-druid', 'dragon-knight',
                   'bloodseeker', 'windranger', 'arc-warden', 'dark-seer', 'doom',
                   'kunkka', 'visage', 'hoodwink', 'spirit-breaker', 'ogre-magi',
                   'winter-wyvern', 'warlock', 'undying')
    MatchupsDir = (Resolve-Path (Join-Path $PSScriptRoot '..\ref\dota2\matchups')).Path
    GuideDir    = Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')) 'guide'
    MinKept     = 3
    OutFile     = $null
}
New-Item -ItemType Directory -Force $Config.GuideDir | Out-Null
$Config.OutFile = Join-Path $Config.GuideDir 'guide-data-generated.js'

# name -> slug map from OpenDota hero list, npc aliases resolved
$heroList = Invoke-RestMethod -Uri 'https://api.opendota.com/api/heroes' -TimeoutSec 60
$slugAliases = @{
    'doom-bringer' = 'doom'; 'obsidian-destroyer' = 'outworld-destroyer'
    'zuus' = 'zeus'; 'nevermore' = 'shadow-fiend'; 'necrolyte' = 'necrophos'
    'skeleton-king' = 'wraith-king'; 'furion' = 'natures-prophet'
    'life-stealer' = 'lifestealer'; 'antimage' = 'anti-mage'; 'wisp' = 'io'
    'shredder' = 'timbersaw'; 'abyssal-underlord' = 'underlord'
    'windrunner' = 'windranger'
}
$nameToSlug = @{}
$iconBySlug = @{}
foreach ($h in $heroList) {
    $internal = ($h.name -replace '^npc_dota_hero_', '')
    $slug = $internal -replace '_', '-'
    if ($slugAliases.ContainsKey($slug)) { $slug = $slugAliases[$slug] }
    $nameToSlug[$h.localized_name] = $slug
    $iconBySlug[$slug] = $internal
}
function Get-Slug([string] $Name) {
    if ($nameToSlug.ContainsKey($Name)) { return $nameToSlug[$Name] }
    ($Name.ToLower() -replace '[^a-z ]', '' -replace ' ', '-')
}

# overall winrates from the opendota snapshot written by fetch-matchups
$odFile = Get-ChildItem $Config.MatchupsDir -Filter 'opendota-*.json' |
    Sort-Object Name | Select-Object -Last 1
if (-not $odFile) { throw 'opendota-*.json missing, run make fetch-matchups first' }
$od = Get-Content $odFile.FullName -Raw | ConvertFrom-Json

# parse each pool hero md, keep |dis| >= threshold
$packed = @{}
$sourceNote = @{}
foreach ($slug in $Config.Pool) {
    $path = Join-Path $Config.MatchupsDir "$slug.md"
    if (-not (Test-Path $path)) { throw "matchup table missing: $path" }
    $rows = @()
    foreach ($line in Get-Content $path) {
        if ($line -match '^\|\s*([^|]+?)\s*\|\s*(-?[\d.]+)\s*\|\s*(-?[\d.]+)\s*\|\s*(\d+)\s*\|\s*$') {
            $dis = [double]$Matches[2]
            if ([math]::Abs($dis) -ge $Config.Threshold) {
                $rows += [pscustomobject]@{ slug = Get-Slug $Matches[1]; dis = $dis; matches = [long]$Matches[4] }
            }
        }
    }
    if ($rows.Count -lt $Config.MinKept) { throw "$slug kept only $($rows.Count) rows above threshold" }
    $packed[$slug] = ($rows | Sort-Object dis -Descending | ForEach-Object { "$($_.slug):$($_.dis)" }) -join '|'
    $src = (Get-Content $path -TotalCount 3)[2]
    if ($src -notmatch 'de\.dotabuff\.com') { throw "$slug.md is not from the de locale rebuild" }
    $sourceNote[$slug] = 'dotabuff live 2026-09-24 (de locale)'
    Write-Host ("{0,-14} {1,3} rows kept at |dis| >= {2}" -f $slug, $rows.Count, $Config.Threshold)
}

# overall wr for pool heroes
$wr = @{}
foreach ($slug in $Config.Pool) {
    $v = $od.overall_wr_by_slug.$slug
    if ($null -eq $v) { throw "no overall winrate for $slug in $($odFile.Name)" }
    $wr[$slug] = $v
}

$js = @()
$js += '// generated by scripts/build-guide-data.ps1, do not edit by hand'
$js += "// packed rows: enemySlug:dis (dis positive = enemy beats pool hero), |dis| >= $($Config.Threshold)"
$js += 'window.GUIDE_GEN = {'
$js += "  date: '$($Config.Date)',"
$js += "  threshold: $($Config.Threshold),"
$js += '  sources: {'
foreach ($slug in $Config.Pool) { $js += "    '$slug': '$($sourceNote[$slug])'," }
$js += '  },'
$js += '  overallWr: {'
foreach ($slug in $Config.Pool) { $js += "    '$slug': $($wr[$slug])," }
$js += '  },'
$js += '  matchups: {'
foreach ($slug in $Config.Pool) { $js += "    '$slug': '$($packed[$slug])'," }
$js += '  },'
$js += '  iconBySlug: {'
foreach ($k in ($iconBySlug.Keys | Sort-Object)) { $js += "    '$k': '$($iconBySlug[$k])'," }
$js += '  }'
$js += '};'
Set-Content -Path $Config.OutFile -Value $js -Encoding utf8
Write-Host "wrote $(Split-Path $Config.OutFile -Leaf) with $($Config.Pool.Count) heroes"
